var button = document.createElement("button");
button.innerHTML = "Meet your new friend!";

var certificate = document.getElementById("certificate");
certificate.appendChild(button);
button.id = "idk_your_id_here";

const GRUB_IMAGES = [
  ["images/grubby.png", "a grub"],
  ["images/adoptable_grubs/blomgrub.png", "a blomgrub"],
  ["images/adoptable_grubs/purpgrub.png", "a purple grub"],
  ["images/adoptable_grubs/grubchu.png", "a grubchu"],
  ["images/adoptable_grubs/grumbchu.png", "a grumbchu"],
  ["images/adoptable_grubs/arg.png", "an alternate reality grub"],
  ["images/adoptable_grubs/aggrub.png", "an aagrub"],
  ["images/adoptable_grubs/mothgrub.png", "A moth grub"],
  ["images/adoptable_grubs/pengrub.png", "A penguin grub"],
  ["images/adoptable_grubs/adventure_grubby.png", "An adventuring grub"],
  ["images/adoptable_grubs/angel_grubby.png", "An angel grub"],
  ["images/adoptable_grubs/astronaut_grubby.png", "An astronaut grub"],
  ["images/adoptable_grubs/beach_grubby.png", "A beach grub"],
  ["images/adoptable_grubs/beastling_grubby.png", "A grub with a beastling on its head"],
  ["images/adoptable_grubs/cactus_grubby.png", "A cactus grub"],
  ["images/adoptable_grubs/carrot_grubby.png", "A carrot grub"],
  ["images/adoptable_grubs/crystal_grubby.png", "A crystal grub"],
  ["images/adoptable_grubs/devil_grubby.png", "A devil grub"],
  ["images/adoptable_grubs/ditto_grubby.png", "A ditto grub"],
  ["images/adoptable_grubs/fancy_grubby.png", "A fancy grub with a monocle and hat"],
  ["images/adoptable_grubs/flea_grubby.png", "A fluffy flea grub"],
  ["images/adoptable_grubs/flower_grubby.png", "A flower grub"],
  ["images/adoptable_grubs/fox_grubby.png", "A fox grub"],
  ["images/adoptable_grubs/galaxy_grubby.png", "A galaxy grub"],
  ["images/adoptable_grubs/ghost_grubby.png", "A ghost grub"],
  ["images/adoptable_grubs/grubby.png", "An alien grub in a little UFO"],
  ["images/adoptable_grubs/infection_grubby.png", "The infection, given grub form"],
  ["images/adoptable_grubs/lifeblood_grubby.png", "A lifeblood grub with lifeblood wings"],
  ["images/adoptable_grubs/math_grubby.png", "TheMathGrub_314"],
  ["images/adoptable_grubs/mossy_grubby.png", "A mosskin-shaped grub"],
  ["images/adoptable_grubs/mushroom_grubby.png", "A fungal grub"],
  ["images/adoptable_grubs/portal_grubby.png", "A grub peeking through a portal"],
  ["images/adoptable_grubs/pride_grubby.png", "A rainbow-colored grub"],
  ["images/adoptable_grubs/radioactive_shrimp_grubby.png", "A radioactive shrimp grub (from Walmart)"],
  ["images/adoptable_grubs/shade_grubby.png", "A shade grub"],
  ["images/adoptable_grubs/soul_totem_grubby.png", "A soul totem grub"],
  ["images/adoptable_grubs/strawberry_grubby.png", "A strawberry grub"],
  ["images/adoptable_grubs/trans_grubby.png", "A trans grub"],
  ["images/adoptable_grubs/zeronium_grubby.png", "A zeronium grub"]
]

const GRUB_NAMES = [
  "Acid Crawler",
  "Agitha",
  "Ambrose",
  "Baelfly Princess",
  "Beamer",
  "BeeBo",
  "Beeglob",
  "Belkite",
  "Bellowing Bog Beetle",
  "Birdfly",
  "Blastfly",
  "Blaze Salamander",
  "Blitznab",
  "Bloomguard",
  "Blueclaw Spitter",
  "Bobble Grub",
  "Bobbley",
  "Bogeeze",
  "Bolt",
  "Bop",
  "Bounceback",
  "Brigge",
  "Bristleback",
  "Bubbalou Grub",
  "Bubblebee",
  "Bubblebug",
  "Buddeet",
  "Buggly",
  "Bulb Grub",
  "Bulbly",
  "Bulby",
  "Bumble-Beezy",
  "Bumblebee",
  "Bumbles",
  "Bumbleshell",
  "Bumbleshout",
  "Bumblesnout",
  "Bumbly",
  "Bun Bun Grub",
  "Bunbun",
  "Burbly the Snaffler",
  "Burrly",
  "Burrow Grub",
  "Burrower Grub",
  "Burrowie",
  "Butterbug",
  "Buttercup",
  "Butters",
  "Buzz Bugger",
  "Buzz Burr",
  "Buzz One",
  "Buzz",
  "Buzz-Wing",
  "Buzzangler",
  "Buzzbeak",
  "BuzzBee",
  "Buzzbit",
  "Buzzboop",
  "Buzzbug",
  "Buzzbuzz",
  "Buzzby",
  "Buzzer",
  "Buzzfuzz",
  "Buzzitty",
  "Buzzler",
  "Buzzly",
  "Buzzsaw Grub",
  "Buzzscuttle",
  "Buzzwing",
  "Buzzy Bee",
  "Buzzy Blinker",
  "Buzzy the Bzzing Grub",
  "Buzzy",
  "Buzzzelworm",
  "Buzzzz",
  "Calitzi",
  "Cardigole",
  "Cashew Cutter",
  "Cave Glow Cocoon",
  "Chalkgrub",
  "Char Grub",
  "Charged Fat Grub",
  "Charmer Snail",
  "Charred Slugsaw",
  "Charvee",
  "Cheepy",
  "Chewbuggie",
  "Chewi",
  "Chewie",
  "Chillbumper",
  "Chillcoat",
  "Chimera Grub",
  "Chipmunk",
  "Chipotle",
  "Chipper",
  "Chirp",
  "Chirpee",
  "Chirper",
  "Chirping Grub",
  "Chirpsy",
  "Chirpy",
  "Chirruping Grub",
  "Chittering Glider",
  "Cholli",
  "Chomper",
  "Chompy the Chomping Grub",
  "Chub-Chub",
  "Chubb Bug",
  "Chubbles",
  "Chubbly",
  "Chubby Cheeks Grub",
  "Chubsy",
  "Chubwing",
  "Chugga-Bug",
  "Chunky Grubbles",
  "Chunky Grubby",
  "Churlbugg",
  "Churrworm",
  "Cinder-Grub",
  "Cinderbug",
  "Cinderpillar",
  "Clacco the Chirrup",
  "Clacksnout",
  "Clawcrawler",
  "Clawkin",
  "Clicky",
  "Clinger Grub",
  "Clitch",
  "Cloppy",
  "Cloth Wisp",
  "Coggles the Crawler",
  "Consume-a-lot",
  "Convenient Grub",
  "Cosy Grubbinator",
  "Crawly",
  "Creepster",
  "Crestog",
  "Cricket",
  "Crimson Skitterling",
  "Crispersnip",
  "Crossroad-cruncher",
  "Crumbly",
  "Crumpet",
  "Crunchlette",
  "Crystalline Crawler",
  "Crystallis",
  "Cuddlebud",
  "Cuddlee",
  "Cuddles",
  "Cuddlesquirm",
  "Cuddly Crawly",
  "Cuddly Grubs",
  "Curley",
  "Curli",
  "Curlicue",
  "Curly Q",
  "Curly the Curlicue Grub",
  "Curly",
  "Cutesy-Paws",
  "Cutie Caterpillar",
  "Cutie Chitter",
  "Cutie Pie Grub",
  "Cutie Wiggler",
  "Cuttlebitty",
  "Cuttleboo",
  "Cuttlebu",
  "Cuttlebug",
  "Cuttletrunk",
  "Cybuggler",
  "Daisy",
  "Dandy Grub",
  "Dartly",
  "Dawn Grub",
  "Deep Grub",
  "Deep Wriggler",
  "Deep-delver",
  "Deepglide the Wriggler",
  "DeepScale Grub",
  "Deepwing",
  "Deeree",
  "Desolation Moth",
  "Diamondeye",
  "Dirt Muncher",
  "Dirt Roo",
  "Dirtmoss",
  "Doodle Bug",
  "Doodle",
  "Dottie",
  "Dozy",
  "Dream Grub",
  "Drifter Worm",
  "Dugong",
  "Dusk Thief",
  "Duskwings",
  "Dust Drake",
  "Dust Grub",
  "Dust-bunny",
  "Dustfly",
  "Dustmound",
  "Dustwing",
  "Earendel",
  "Eileen the Hungry",
  "Entoza",
  "Essence Eater",
  "Extrest Grub",
  "Feathery Fritter",
  "Fidget",
  "Fifi the Friendly Grub",
  "Figglepop",
  "Figgolem",
  "Figgy",
  "Fire Dreamer",
  "Fire Lashbug",
  "Fizzworm",
  "Fizzy",
  "Flicker",
  "Flik",
  "Flipo",
  "Flitt",
  "Flitterbug",
  "Flitzy",
  "Flop 'Em",
  "Floppies",
  "Floppy",
  "Fluffa",
  "Flufftastic Grub",
  "Fluffy",
  "Fluffy-Feathers",
  "Flukemstrum",
  "Flutter",
  "Flutterbee",
  "Flutterbug",
  "Fracto",
  "Friggs",
  "Frilly",
  "Frizzlefly",
  "Fuddy",
  "Fumtum",
  "Fungal Emberfly",
  "Fungal Forager",
  "Fungal Wick",
  "Fungey Shrubster",
  "Fungicle",
  "Fungiface",
  "Fungmin",
  "Fungoar",
  "Fungoid",
  "Fungoidsting",
  "Fungus-Lord",
  "Fungusfly",
  "Fury Sprout",
  "Fuzzball",
  "Fuzzer",
  "Fuzzkins",
  "Fuzzlemuff",
  "Fuzzums",
  "Fuzzy Flutter",
  "Fuzzy Grub",
  "Fuzzy Nubble",
  "Fuzzy Wuzzy Grub",
  "Fuzzy",
  "Fuzzy-Puppy",
  "Fuzzywuzz",
  "Gallop Mudbug",
  "Gambril",
  "Garpede",
  "Gascoigne Grub",
  "Giggle Wiggler",
  "GiggleBug",
  "Gigglebuggie",
  "Giggles",
  "Gizmo",
  "Gizmo-Gobble",
  "Gizzlaw",
  "Gleeble",
  "Glibglop",
  "Glider",
  "Glimfly",
  "Glimglom",
  "Glimmer",
  "Glimmerfly Grove",
  "Glimworm",
  "Glintmoth-Grub",
  "Glitchy",
  "Glitter Grub",
  "Glitter",
  "Glitterbug",
  "Glittersnaps",
  "Glitterwing",
  "Glitz",
  "Glitzie",
  "Gloam",
  "Gloam-gnawer",
  "Glooble",
  "Gloom-Grub",
  "Gloomnip",
  "Gloomy",
  "Gloop",
  "Glooper",
  "Gloopy",
  "Glopling",
  "Glossy",
  "Glow Grub",
  "Glowbud",
  "Glowfly Grub",
  "Glowing Grub",
  "Glowing Snail",
  "Glowing Wriggler",
  "Glowmaggot",
  "Glowmo",
  "Glowwormshroom",
  "Glowygrub",
  "Glutterfly",
  "Gobble",
  "Gooble",
  "Goobling",
  "Gooey Grub",
  "Gooey",
  "Goomok",
  "Gorgot",
  "Gormaander",
  "Grave Wasp",
  "Gravity Grub",
  "Grealez",
  "Great Nailsage Sly",
  "Greber the Grub",
  "Greepbuzz",
  "Grey Hunter",
  "Greyfur",
  "Gribbler",
  "Gribby",
  "Grim Hornet",
  "Grimburly",
  "Grimfly",
  "Grimm Grub",
  "Grimmalle",
  "Grimmer",
  "Grimmermite",
  "Grimmite",
  "Gripper Grub",
  "Grit-Grub",
  "Gritburger",
  "Gritlily",
  "Grizzled Snoutworm",
  "Grobblefly",
  "Grogger",
  "Groggo",
  "Groob",
  "Groovin' Grubby",
  "Groovy Grub",
  "Gropler",
  "Grouchy",
  "Grounder",
  "Grub Blubb",
  "Grub Egg",
  "Grub Glimmer",
  "Grub Groove",
  "Grub Hopper",
  "Grub Knight",
  "Grub Nibble",
  "Grub Pie",
  "Grub Sluggard",
  "Grub Snugglers",
  "Grub Sweeper",
  "Grub the Builder",
  "Grub the Conqueror",
  "Grub Tubble",
  "Grub's Grotto",
  "Grub's Knees",
  "Grub-a-Boo",
  "Grub-a-Bub",
  "Grub-a-Bye",
  "Grub-a-Bye-Baby",
  "Grub-a-Dab-Do",
  "Grub-a-Doodle-Do",
  "Grub-a-Dub-Dub",
  "Grub-a-Fied",
  "Grub-a-Glow",
  "Grub-a-Knot",
  "Grub-a-Licious",
  "Grub-a-Lot",
  "Grub-a-Lub-Dub",
  "Grub-a-Lumpkin",
  "Grub-a-Mania",
  "Grub-a-Munchkin",
  "Grub-a-Nator",
  "Grub-a-Rama",
  "Grub-a-Roo",
  "Grub-a-Saurus",
  "Grub-a-Tangle",
  "Grub-a-Thon",
  "Grub-a-Tron",
  "Grub-a-Tude",
  "Grub-a-Wiggler",
  "Grub-Adore",
  "Grub-B-Rumble",
  "Grub-Grub-Grumble",
  "Grub-in-the-Rough",
  "Grub-N-Go",
  "Grub-o-Matic",
  "Grub-of-the-Deep",
  "Grub-on-the-Go",
  "Grub-tacular",
  "Grub-Tastic!",
  "Grub-tastic",
  "Grub-topia",
  "Grub-with-Glee",
  "Grubadon the Mighty",
  "Grubadon",
  "Grubadoo",
  "Grubador",
  "Grubadro",
  "Grubakin",
  "Grubaldo",
  "Grubalicious the Hungry",
  "Grubalicious",
  "Grubalina",
  "Grubanoff",
  "Grubard the Adventurous",
  "Grubard",
  "Grubaroo",
  "Grubb",
  "Grubbb",
  "Grubba-Do",
  "Grubbar",
  "Grubbarina the Fearless",
  "Grubbarina",
  "Grubber Bug",
  "Grubber",
  "Grubberella",
  "Grubberfest",
  "Grubberfly",
  "Grubberiffic",
  "Grubberific",
  "Grubbering",
  "Grubberlin",
  "Grubberling",
  "Grubbernaut",
  "Grubberoo",
  "Grubbers the Grubbing Grub",
  "Grubbers",
  "Grubbersnout",
  "Grubbert",
  "Grubberto the Wise",
  "Grubberto",
  "Grubbertus the Cautious",
  "Grubbertus",
  "Grubbies",
  "Grubbily-Goo",
  "Grubbin Huggins",
  "Grubbin",
  "Grubbing Along",
  "Grubbing Around",
  "Grubbing for Glory",
  "Grubbing for Gold",
  "Grubbing in the Dark",
  "Grubbing it Out",
  "Grubbing Out",
  "Grubbing the Night Away",
  "Grubbing",
  "Grubbit",
  "Grubble Blob",
  "Grubble Bop",
  "Grubble Bug",
  "Grubble Dazzle",
  "Grubble Grubs",
  "Grubble Gum",
  "Grubble Mc Grubberson",
  "Grubble the Grub",
  "Grubble",
  "Grubbleberry",
  "Grubblebottom",
  "Grubblebug",
  "Grubblefritz",
  "Grubblegum",
  "Grubblegut the Gluttonous",
  "Grubbles the Grub",
  "Grubbles",
  "Grubblet",
  "Grubbletina the Curious",
  "Grubbletina",
  "Grubbleton",
  "Grubbletop the Agile",
  "Grubbletop",
  "Grubblette",
  "Grubblewing",
  "Grubbleworm",
  "Grubblin' Gourmand",
  "Grubbling Along",
  "Grubblob",
  "Grubbly Bear",
  "Grubbly Goodness",
  "Grubbly Grubster",
  "Grubbly Wubbly",
  "Grubbly",
  "Grubbly-Go-Round",
  "Grubbo",
  "Grubboon",
  "Grubbun",
  "Grubbus the Playful",
  "Grubbus",
  "Grubby Dizzy-Goo",
  "Grubby Friend",
  "Grubby Galore",
  "Grubby Gatherings",
  "Grubby Glider",
  "Grubby Glimmer",
  "Grubby Groove Grub",
  "Grubby Grub-Grub",
  "Grubby Grubber",
  "Grubby Grubberoo",
  "Grubby Guts",
  "Grubby Little Buddies",
  "Grubby Little Grub",
  "Grubby McBuggy",
  "Grubby McFly",
  "Grubby the Grub",
  "Grubby the Grubber",
  "Grubby",
  "Grubby's Groove",
  "Grubby-Munchkin",
  "Grubby-Wubby-Do",
  "Grubbydoodle",
  "Grubcap",
  "Grubclaw",
  "Grubelicious",
  "Grubelina the Magnificent",
  "Grubelina",
  "Grubella",
  "Grubelord the Ruler",
  "Grubelord",
  "Gruber",
  "Gruberella",
  "Gruberino",
  "Grubetta",
  "Grubette",
  "Grubglider",
  "Grubguard the Thirsty",
  "Grubikov",
  "Grubina",
  "Grubington",
  "Grubito",
  "Grubius Maximus",
  "Grubius",
  "Grubkin",
  "Gruble",
  "Grublet",
  "Grublin the Swift",
  "Grublin",
  "Grublina the Elegant",
  "Grublina",
  "Grubling Groove",
  "Grubling",
  "Grubloaf",
  "Grublus",
  "Grublyn",
  "Grubnose",
  "Grubolio",
  "Grubox",
  "Grubrick the Brave",
  "Grubrick",
  "Grubrose",
  "Grubs-a-Little",
  "Grubs-a-Lot",
  "Grubs-a-Moderate-Amount",
  "Grubsby",
  "Grubsey",
  "Grubsley",
  "Grubslinger the Quick",
  "Grubslinger",
  "Grubson the Mischievous",
  "Grubson",
  "Grubspike",
  "Grubstache",
  "Grubster the Great",
  "Grubster",
  "Grubsterino",
  "Grubswaddle",
  "Grubswiggle",
  "Grubsworth",
  "Grubsy",
  "Grubtastic",
  "Grubula the Enigmatic",
  "Grubula",
  "Grubules",
  "Grubulisk",
  "Grubulon the Stealthy",
  "Grubulon",
  "Grubulous Maximus",
  "Grubulous",
  "Grubulus",
  "Grubward",
  "Grubwatcher",
  "Grubzilla the Legendary",
  "Grubzilla",
  "Gruffa",
  "Grum",
  "Grumble Grub",
  "Grumble",
  "Grumblebee",
  "Grumblethorn",
  "Grumbleweed",
  "Grumblewort",
  "Grumm",
  "Grumps",
  "Grumpshrimp",
  "Grumpty",
  "Grumptysnout",
  "Grumpus",
  "Grumpy Grubkin",
  "Grumworm",
  "Grumwyrm",
  "Gruzzer",
  "Gruzzle",
  "Gruzzlet",
  "Gruzzly",
  "Guardian Grub",
  "Gully",
  "Gumbloom",
  "Gumbo",
  "Gumby",
  "Gummy Grub",
  "Gussel",
  "Gust Grub",
  "Gutterfly",
  "Happy",
  "Heavy Shade",
  "Herky",
  "Hiccup",
  "Highlighter",
  "Hipper",
  "Hive Keeper",
  "Hive Knight",
  "Hive-hopper",
  "Hivebark",
  "Hivebound Honey",
  "Hivekeeper",
  "Hivelord",
  "Hivewing",
  "Hollow Eel Grub",
  "Honey Buns",
  "Honey Hopper",
  "Honeybae",
  "Honeybun",
  "Honeycomb Grub",
  "Honeycomb",
  "Hooded Stranger",
  "Hopper Husky",
  "Hopper",
  "Hoppin' Joe",
  "Hoppit",
  "Hoppity",
  "Hopple",
  "Hoppy",
  "Hops",
  "Hotnest Grub",
  "Hovering Hermit",
  "Huffleg",
  "Hug-A-Bug",
  "Hushwing",
  "Inkback",
  "Iridbug",
  "Itchy",
  "Itsy Grub",
  "Jellie",
  "Jelly Grub",
  "Jen Jen",
  "Jeremothy",
  "Jeweldrop",
  "Jiggles",
  "Jiggly Joe",
  "Jiggly",
  "Jingle",
  "Jinglebug",
  "Jitter",
  "Jitterbug",
  "Jittery Grub",
  "Jittery",
  "Joltin' Grub",
  "JourneyBite",
  "Jumpcale",
  "Jumpfeather",
  "Jumppup",
  "King Grist",
  "King Mould",
  "Knickknacker",
  "Knightly Delight Grub",
  "Knitwisp",
  "Knocker-Noggin",
  "Labyrinth Grub",
  "Lantern Grub",
  "Lapotch",
  "Larveaureon",
  "Larvy",
  "Leafy",
  "Lichen Hopper",
  "Light Devourer",
  "Lightdarter",
  "Lil' Wriggler",
  "Lilygrub",
  "LittleMiso",
  "Loom Grub",
  "Loopy",
  "Lumafly",
  "Lumarok",
  "Luminary Grub",
  "Lurker",
  "Maggotcloud the Voracious",
  "Maggotry",
  "Maggretta",
  "Magmagrub",
  "Mantis Lord",
  "Mantisclaw",
  "Mantraphagus the Glutton",
  "Markfruit-Grub",
  "Mato Grub",
  "Mawlek",
  "Mawmaw",
  "Mender Grub",
  "Meregol",
  "Miffy",
  "Millie the Milling Grub",
  "Mire",
  "Mist-muncher",
  "Mite-Mite",
  "Mitey",
  "Mittens",
  "Moldmarshal",
  "Molemite",
  "Moon Hopper",
  "Mordant the Ancient",
  "Moskit",
  "Mosquibug",
  "Mosquito",
  "Moss Grub",
  "Moss Matter",
  "Moss Mound Munchkin",
  "Mossbinder",
  "Mosskin",
  "Mosstail",
  "Moth Skitterling",
  "Moth Tribe Shaman",
  "Moth",
  "Mothexander",
  "Mothfly",
  "Mothgracious",
  "Mothnathan",
  "Mothwing",
  "Mothy",
  "Mr. Chomps",
  "Muckoo",
  "Mud Catterpillar",
  "Mud Puff",
  "Muffin",
  "Muffle Wisp",
  "Muncher",
  "Munchkin",
  "Munchmoth",
  "Munchy",
  "Mushaboom",
  "Mushroom Mage",
  "Mushy",
  "Mysticaline",
  "N4ll Beetle",
  "Nail Bug",
  "Nail Clipper",
  "Nail Grubble",
  "Nailbirb",
  "Nailbuzzer",
  "Nailclaw",
  "Nailshroom",
  "Nailwhirl",
  "Narelle",
  "Nature Grub",
  "Necromancer",
  "Nectar Eater",
  "Needlemane",
  "Needler",
  "Needleshell",
  "Needleworm",
  "Needloth",
  "Neleb",
  "Nevermore Grub",
  "Nezzrazz",
  "Nibble",
  "Nibblebug",
  "Nibbledonk",
  "Nibbler",
  "Nibbles",
  "Nibblesnout",
  "Nibbly",
  "Nibbs the Bug",
  "Niblet",
  "Nimble",
  "Nimbletrot",
  "Noble Nibbler",
  "Noctecoon",
  "Nodor",
  "Noodle",
  "Nubbins",
  "Oozy the Slime",
  "Orph the Nocto",
  "Ossean",
  "Pale Bearer",
  "Pale Wriggler",
  "Pancake Grub",
  "Pandemite",
  "Patter",
  "Pebbles",
  "Peekaboo",
  "Peekagrub",
  "Peepers",
  "Perky Pillbug",
  "Perky",
  "Perplexed Grub",
  "Phantom Spawn",
  "Pillar Grub",
  "Pillowbugs",
  "Pillurble",
  "Pinchy",
  "Pinstripe",
  "Pippa",
  "Pippin",
  "Pippy",
  "Pipsqueak",
  "Pitter Plodder",
  "Plated Clawsnail",
  "Plodder",
  "Plopkins",
  "Pluckabee",
  "Plumombre",
  "Plump",
  "Plush Bug",
  "Poko",
  "Ponder",
  "Poofy",
  "Poppet",
  "Poppy",
  "Pranceworm",
  "Prickle",
  "Prickly Grubbee",
  "Prickly Pod",
  "Puddle",
  "Puddles",
  "Puddley",
  "Puddly",
  "Puffapod",
  "Puffcoil",
  "Pupa",
  "Pupperoni",
  "Puru",
  "Quacky",
  "Quaggle",
  "Queen Mantis Shade",
  "Quirkle",
  "Quirper",
  "Redcap",
  "Refurbished Grub",
  "Rickle",
  "Ripple",
  "Royal Grub",
  "Rustle",
  "Rustwasp",
  "Rustybug",
  "Safe Creeper",
  "Saltsquirm",
  "Salubra Skulker",
  "Sap Grub",
  "Sappyfly",
  "Scabblefly",
  "Scamp",
  "Scamper",
  "Scampers",
  "Scarabug",
  "Scavenger Grub",
  "Schnookie",
  "Scootaloo",
  "Scorupt",
  "Scree-Grub",
  "Scrobbler",
  "Scrubby",
  "Scrunchy",
  "Scurry",
  "Scuttle",
  "Scuttler",
  "Scuttles",
  "Scuttlesnout",
  "Scuttletail",
  "Scuttly",
  "Seeker Grub",
  "Shade Beast",
  "Shade Edge",
  "Shade Lurker",
  "Shadechomp",
  "Shadeclaw",
  "Shadefly",
  "Shadow Buzzer",
  "Shadow Flitter",
  "Shadow Grub",
  "Shadow Shimmer",
  "Shadow-Grub",
  "Shadowdancer",
  "Shelien",
  "Shell Hopper",
  "Shellback",
  "Shellglider",
  "Shimmerbug",
  "Shinee",
  "Shriek Bun",
  "Shrimbly",
  "Shyrtle",
  "Sideslip",
  "Silk Gatherer",
  "Silk Sensei",
  "Silksnail",
  "Silverhopper",
  "Silverwing",
  "Sirius",
  "Skedaddle",
  "Skeetle",
  "Skele Grub",
  "Skip",
  "Skipley",
  "Skipper Skittles",
  "Skipper",
  "Skipperhopper",
  "Skippety",
  "Sleepy Slugger",
  "Slick Grubster",
  "Slick",
  "Slickles",
  "Slime Galore",
  "Slimeball",
  "Slimebite",
  "Slimeface",
  "Slimefoot",
  "Slimemite",
  "Slimeton",
  "Slimy",
  "Slipper",
  "Slither",
  "Slitherwing",
  "Sliverbug",
  "Slivers",
  "Slop",
  "Slopper",
  "Sludge Eel",
  "Sludge",
  "Sludgeon",
  "Slumbercat",
  "Slurp",
  "Slurper",
  "Slurpy",
  "Slushie",
  "Slyder",
  "Smiley Grub",
  "Smiley Skitter",
  "Snaggle",
  "Snailer",
  "Snapperfly",
  "Snazzles",
  "Snibble",
  "Snibbob the Gluttonous",
  "Snicker Scuttler",
  "Snicker",
  "Snickerdoodle",
  "Snickety",
  "Snickle the Snurble",
  "Snookums",
  "Snoozy Grub",
  "Snuffly",
  "Snug",
  "Snuggle Bug",
  "Snuggle",
  "Snugglebug",
  "Snugglefly",
  "Snuggles",
  "Snuggles-Wiggles",
  "Snuggly",
  "Snuggy Grub",
  "Softmaker",
  "Solon",
  "Soot Slug",
  "Soul Grub",
  "Soulgazer",
  "Sparkle",
  "Sparklewiggler",
  "Sparklewing",
  "Sparky",
  "Speckle",
  "Spikeroot",
  "SpindlyDoodle",
  "Spiny Wurm",
  "Spiral Grub",
  "Spirit Grub",
  "Spittlegrub",
  "Sploshy Grub",
  "Spore Cloud",
  "Sprout",
  "Spudstar",
  "Squabble",
  "Squeaker",
  "Squeaks",
  "Squeakums",
  "Squeaky",
  "Squeeker",
  "Squiggle",
  "Squiggly",
  "Squiggy",
  "Squiglet",
  "Squigzy the Goop",
  "Squink",
  "Squirm Blurm",
  "Squirm Grub",
  "Squirm",
  "Squirmilla",
  "Squirming Seeker",
  "Squirmkin",
  "Squirmles",
  "Squirmly",
  "Squirmy",
  "Squirmz",
  "Squirt",
  "Squirtie",
  "Squirty",
  "Squish",
  "Squish-Munch",
  "Squishy",
  "Squishypaw",
  "Squisk",
  "Sroadign",
  "Stagmane",
  "Staincrab",
  "Stalwart Grub",
  "Stardustbug",
  "Stingbulb",
  "Stingtail",
  "Stingwing",
  "Stitchy",
  "Stone Skimmer",
  "Stonejaw",
  "Storm Crawler",
  "Strisp",
  "Stubby Grub",
  "Stumpy",
  "Sunny",
  "Supergrub",
  "Swarmlord",
  "Swarmstone",
  "Sweet Burrower",
  "Swoofulk",
  "Swoonworm",
  "Swoop",
  "Tadpink",
  "Tanglebloom",
  "Tart",
  "Tater Tot",
  "Tater",
  "Tendril",
  "The Fargus Flycatcher",
  "The Greasy Grub",
  "The Grub-inator",
  "The Molted Sentinel",
  "The Splinter Grub",
  "The Void Wing",
  "The Waking Shadow",
  "Thin-Mud",
  "Thistle Guard",
  "Thragg",
  "Three-Eye Grubshroom",
  "Thrumble",
  "Thumper",
  "Tickle",
  "Tickly",
  "Tinkerfly",
  "Tinny",
  "Tiny Troopers",
  "Tiny Turnip",
  "Tiny",
  "Tiny-Crawler",
  "Tippy-Toots",
  "Toblerone",
  "Tootle",
  "Trailblazer Grub",
  "Trappledoof",
  "Trinket",
  "Trot",
  "Trotter",
  "Truffle Mite",
  "Tubbelup",
  "Tubby",
  "Tuffly",
  "Tumble Grub",
  "Tumbly Bubbly",
  "Tummy Sprout",
  "Tunnel Grub",
  "Twiggle",
  "Twiggles",
  "Twiggy",
  "Twinkles",
  "Twitch",
  "Twitchy",
  "Upside-Down Grub",
  "Vengeful Spirit",
  "Venomer",
  "Vermilion",
  "Vespa Grub",
  "Violoid",
  "Viridescent Flytrap",
  "Viridian Grub",
  "Viscount Chorus",
  "Vivibulb",
  "Void Gazer",
  "Void Maze",
  "Wallworm",
  "Waltz",
  "Wambus",
  "Wandering Grub",
  "Watcher Knight",
  "Watchergleam",
  "Weebugs",
  "Wegsnar",
  "Whimby",
  "Whimsy",
  "Whiskers",
  "Whiskring",
  "Whitecap",
  "Wiggle n' Jiggle",
  "Wiggle",
  "Wiggler",
  "Wiggles the Wiggly Grub",
  "Wiggles",
  "Wigglesworth",
  "Wigglewobble",
  "Wigglez",
  "Wiggly Grub",
  "Wiggly Wisp",
  "Wiggly",
  "Wild Grub",
  "Wilkling",
  "Willow Weevil",
  "Wingmutter",
  "Wingy the Winged Grub",
  "Wire Bug",
  "Wisp Grub",
  "Wobble",
  "Wobbles",
  "Wobblewiggle",
  "Wolf Knight",
  "Wolfshell",
  "Woofer",
  "Woogle",
  "Wormly",
  "Wormtail",
  "Wormy",
  "Wrigglar",
  "Wriggle Grub",
  "Wriggle",
  "Wrigglee",
  "Wrigglepuff",
  "Wriggler",
  "Wrigglermoth",
  "Wrigglers",
  "Wriggles",
  "Wriggling Chap",
  "Wriggly",
  "Wrinkles",
  "Writhy",
  "Xeamless",
  "Yapper",
  "Zap",
  "Zote the Mighty"
];
const GRUB_SURNAMES = [
  " Beeglob",
  " Belkite",
  " Blob",
  " Bloomguard",
  " Bristleback",
  " Bubblebug",
  " Bug",
  " Bumble-Beezy",
  " Bumbleshell",
  " Bumblesnout",
  " Butterbug",
  " Buzzbit",
  " Buzzboop",
  " Buzzscuttle",
  " Buzzzelworm",
  " Chillcoat",
  " Chirruping Grub",
  " Chubwing",
  " Churlbugg",
  " Cinderbug",
  " Cinderpillar",
  " Clacksnout",
  " Clawcrawler",
  " Clawkin",
  " Crispersnip",
  " Crossroad-cruncher",
  " Crystallis",
  " Cuddlesquirm",
  " Cutesy-Paws",
  " Cuttlebitty",
  " Cuttletrunk",
  " Deep-delver",
  " Deepwing",
  " Dustmound",
  " Essence Eater",
  " Flitterbug",
  " Fluffy-Feathers",
  " Flutterbee",
  " Fungicle",
  " Fungmin",
  " Fungoidsting",
  " Fungusfly",
  " Fuzzlemuff",
  " Fuzzy-Puppy",
  " Gigglebug",
  " Gizmo-Gobble",
  " Gizzlaw",
  " Gleeble",
  " Glibglop",
  " Glimworm",
  " Glitter",
  " Glitterbug",
  " Glitterwing",
  " Gloam-gnawer",
  " Glopling",
  " Glowbud",
  " Greepbuzz",
  " Greyfur",
  " Gritburger",
  " Grobblefly",
  " Grub",
  " Grubberfly",
  " Grubbin",
  " Grubbing",
  " Grubbler",
  " Grubbydoodle",
  " Grubcap",
  " Grubclaw",
  " Grubglider",
  " Grublet",
  " Grumpshrimp",
  " Grumpty",
  " Gumbo",
  " Gutterfly",
  " Hive-hopper",
  " Hivebark",
  " Hivekeeper",
  " Hivelord",
  " Honeycomb",
  " Hushwing",
  " III",
  " Inkback",
  " IV",
  " IX",
  " Jeweldrop",
  " Knitwisp",
  " Knocker-Noggin",
  " Lapotch",
  " Lilygrub",
  " Lumafly",
  " Magmagrub",
  " Mantisclaw",
  " Mawmaw",
  " Mist-muncher",
  " Moldmarshal",
  " Mossbinder",
  " Mosstail",
  " Moth",
  " Needlemane",
  " Needler",
  " Needleworm",
  " Nezzrazz",
  " Nibblesnout",
  " Nimble",
  " Nimbletrot",
  " Pandemite",
  " Pranceworm",
  " Redcap",
  " Rustybug",
  " Saltsquirm",
  " Scabblefly",
  " Scuttlesnout",
  " Shadeclaw",
  " Shadefly",
  " Shadowdancer",
  " Shellback",
  " Shellglider",
  " Sideslip",
  " Silverbug",
  " Silverhopper",
  " Singbulb",
  " Skeetle",
  " Slimeball",
  " Slimeface",
  " Slimeite",
  " Slitherwing",
  " Slumbercat",
  " Snuggles-Wiggles",
  " Softmaker",
  " Sparklewiggler",
  " Spindlydoodle",
  " Squish-Munch",
  " Stagmane",
  " Stardustbug",
  " Stingtail",
  " Stingwing",
  " Stonejaw",
  " Supergrub",
  " Tanglebloom",
  " the Adventurous",
  " the Agile",
  " the Brave",
  " the Cautious",
  " the Curious",
  " the Elegant",
  " the Enigmatic",
  " the Fearless",
  " the Gluttonous",
  " the Great",
  " the Hungry",
  " the Legendary",
  " the Magnificent",
  " the Mighty",
  " the Mischievous",
  " the Monarch of Grubland",
  " the Playful",
  " the Quick",
  " the Ruler",
  " the Stealthy",
  " the Swift",
  " the Void Wing",
  " the Wise",
  " Thin-Mud",
  " Tinkerfly",
  " Tiny-Crawler",
  " Tippy-Toots",
  " Trappledoof",
  " V",
  " VI",
  " VII",
  " VIII",
  " Vivibulb",
  " Wallworm",
  " Watchergleam",
  " Whiskring",
  " Wigglesworth",
  " Wigglewobble",
  " Wiggly",
  " Wingmutter",
  " Wobblewiggle",
  " Wolfshell",
  " Wrigglepuff",
  " Wrigglermoth",
  ", Esq.",
  ", Jr.",
  ", PhD.",
  ", Sr."
];
const GRUB_TITLES = [
  "Admiral",
  "Archduchess ",
  "Archduke ",
  "Baron ",
  "Baroness ",
  "Captain ",
  "Count ",
  "Countess ",
  "Dr. ",
  "Duchess ",
  "Duke ",
  "Earl ",
  "Emperor ",
  "Empress ",
  "General ",
  "Grand Vizier ",
  "Grub ",
  "Judge ",
  "King ",
  "Knight ",
  "Lady ",
  "Lil\' ",
  "Lord ",
  "Madam ",
  "Marquioness ",
  "Marquis ",
  "Miss ",
  "Monarch ",
  "Mr. ",
  "Mrs. ",
  "Mx. ",
  "President ",
  "Prime Minister ",
  "Prince ",
  "Princess ",
  "Professor ",
  "Queen ",
  "Saint ",
  "Ser ",
  "Sir ",
  "Syr ",
  "The ",
  "The Brave ",
  "The Formidable ",
  "The Generous ",
  "The Grand ",
  "The Great ",
  "The Honourable ",
  "The Magnificent ",
  "The Mighty ",
  "Tsar ",
  "Viscount ",
  "Viscountess ",
  "Vizier "
];
const PRONOUNS = [
  'she/her',
  'she/her',
  'she/her',
  'she/her',
  'she/her',
  'he/him',
  'he/him',
  'he/him',
  'he/him',
  'he/him',
  'they/them',
  'they/them',
  'they/them',
  'they/them',
  'they/them',
  'fae/faer',
  'xe/xem',
  'it/its',
  'ze/zir',
  'ey/em',
  've/ver',
  'grub/grubs'
];
const GRUB_FOODSTUFFS = [
  'Anise',
  'Apple tree leaves',
  'Aster',
  'Azalea',
  'Bigflower Pawpaw',
  'Birch',
  'Birthwort Vines',
  'Cabbage',
  'Carrot',
  'Celery',
  'Cherry tree leaves',
  'Chervil',
  'Cilantro',
  'Culantro',
  'Clover',
  'Common Hoptree',
  'Coriander',
  'Daisies',
  'Dill',
  'Dutchman’s pipe',
  'Dwarf Pawpaw',
  'Fennel',
  'Golden Alexander',
  'Grapefruit Leaves',
  'Laurel',
  'Lemon Leaves',
  'Lilac',
  'Magnolia',
  'Mallow',
  'Milkweed',
  'Mint',
  'Netted Pawpaw',
  'Nettle',
  'Olive',
  'Pansies',
  'Parsley',
  'Parsnip',
  'Passionflowers',
  'Pipevine',
  'Plantains',
  'Plum tree leaves',
  'Prickly ash',
  'Queen Anne’s Lace',
  'Rose Leaves',
  'Roses Petals',
  'Rue',
  'Sassafras',
  'Sea Torchwood',
  'Smallflower Pawpaw',
  'Snapdragon',
  'Spicebush',
  'Strawberry',
  'Sweet Orange Leaves',
  'Tangerine Leaves',
  'Thistle',
  'Tuliptree',
  'Violets',
  'Virginia snakeroot',
  'Wild Lime',
  'Willow',
  'Woolly Pawpaw'
];
const GRUB_PERSONALITIES = [
  'Absentminded',
  'Adaptable',
  'Adventurous',
  'Anxious',
  'Articulate',
  'Brave',
  'Calm',
  'Clumsy',
  'Competitive',
  'Confident',
  'Courageous',
  'Crafty',
  'Curious',
  'Detail-oriented',
  'Determined',
  'Discerning',
  'Eccentric',
  'Explorer',
  'Focused',
  'Friendly',
  'Generous',
  'Heroic',
  'Idealistic',
  'Imaginative',
  'Independent',
  'Inquisitive',
  'Kind',
  'Loyal',
  'Meandering',
  'Optimistic',
  'Outspoken',
  'Patient',
  'Peaceful',
  'Persistent',
  'Personable',
  'Playful',
  'Quiet',
  'Quirky',
  'Reliable',
  'Reserved',
  'Resourceful',
  'Self-conscious',
  'Sensitive',
  'Shy',
  'Silly',
  'Sociable',
  'Solitary',
  'Sophisticated',
  'Spontaneous',
  'Tenacious',
  'Tireless',
  'Trusting',
  'Tough',
  'Whimsical'
];
const MIMIC_NAMES = [
  'Acid Licker',
  'Beardy Beetle',
  'Blobtodder',
  'Blocky Scarab',
  'Bonebite',
  'Burrower bug',
  'Buzzing Bimble',
  'Carrion Chomper',
  'Char Swarmer',
  'Chikkin Cringer',
  'Chirpy',
  'Chomp Bug',
  'Chomperkin',
  'Clampy Clinger',
  'Clicky Crawler',
  'Cling Dweller',
  'Clomping Chomper',
  'Crawlclaw',
  'Crawlfang',
  'Crawlipede',
  'Croakershrike',
  'Cutterfly',
  'Dirtminder',
  'Faltail',
  'Fire Bloon',
  'Fleabite',
  'Footwriggler',
  'Fossflow',
  'Fungoblin',
  'Funky Chompster',
  'Gabble Glutton',
  'Glopgrub',
  'Glowcap',
  'Glurcher',
  'Glutbuzz',
  'Glutterfly',
  'Gluttock',
  'Gnawer Beetle',
  'Goo Glutton',
  'Greedsquid',
  'Gribbly Gnat',
  'Gristly Grawl',
  'Gritskitter',
  'Grubkin Maw',
  'Grublurk',
  'Grubpup',
  'Grubspinner',
  'Grumble Fly',
  'Grunny Grounder',
  'Gummy Nibbler',
  'Gurgle Gulper',
  'Gutgorger',
  'Gutterfly',
  'Hortling',
  'Joltbug',
  'Jubilant Grobbler',
  'Junk Muddle',
  'Larva Lurker',
  'Ledger Lunger',
  'Maggot Muncher',
  'Mandible Mish-mash',
  'Mantis Muncher',
  'Mardel Grubber',
  'Mazegoose',
  'Meatshield',
  'Mining Masticator',
  'Mossling',
  'Muck Midge',
  'Muckdragger',
  'Munch Monster',
  'Muncher Shrimp',
  'Munchling',
  'Munchy Grubber',
  'Nectarhopper',
  'Needle Nibbler',
  'Nibble Nibbler',
  'Nibble Scuttle',
  'Oily Grubble',
  'Pick Pincher',
  'Plasterskimmer',
  'Plodworm',
  'Plumphog',
  'Pulpdigger',
  'Revelburrow',
  'Root Skulker',
  'Root wriggler',
  'Rumblegut',
  'Scalebrush',
  'Scrap Sniggerer',
  'Scrapfang',
  'Shellshade',
  'Shellshroom',
  'Shish Kabughan',
  'Skelechomp',
  'Skulleach',
  'Slime Pincer',
  'Slimy Slurker',
  'Sludge Slurper',
  'Sludgrin',
  'Slugslip',
  'Slurgslaw',
  'Smack Snack',
  'Smiggy Gnawer',
  'Soggy Spore',
  'Splutch',
  'Spore Sipper',
  'Squishgrub',
  'Stagnant Snacker',
  'Suddenhide',
  'Swooping Scourge',
  'Tarbag',
  'Troghopp',
  'Venomous Vor',
  'Web Wriggler',
  'Wiggleglom',
  'Wild swarm',
];
const MIMIC_FOODSTUFFS = [
  'Blistermoss',
  'Blue Moth Strip',
  'Cables',
  'Deepnest Delights',
  'Dirt Clumps',
  'Dirt Sprouts',
  'Dreamfeast',
  'Dust Moth Bites',
  'Dusty Bun',
  'Effervescent Mush',
  'Failed Experiment Pie',
  'Fey Moth Egg',
  'Flukefin Soup',
  'Flukemarm Egg',
  'Flukemarm Eggs',
  'Fungal Clump Pudding',
  'Fungal Clump',
  'Fungal Core',
  'Fungal Wastes Mushrooms',
  'Fungus Drum',
  'Funicular Fruit',
  'Glowfly Lantern',
  'Glowing Egg',
  'Glowing Wort',
  'Gobbletoots',
  'Great Slashshroom',
  'Grub-style Cake',
  'Grub-style Crepes',
  'Grub-style Fish and Chips',
  'Grub-style Fried Chicken',
  'Grub-style Fries',
  'Grub-style Grilled Cheese',
  'Grub-style Noodle Bowl',
  'Grub-style Pizza',
  'Grub-style Rice',
  'Grubhoney',
  'Heavenly Bulb',
  'Hive Cluster',
  'Hiveborn Soup',
  'Hollow Knight Cake',
  'Hulking Carapace',
  'Jelly Jumps',
  'JELLY Lumpfish',
  'Matozaure Egg',
  'Mist Lurkers',
  'Mosskin Egg',
  'Mycelial Tufts',
  'Nail Bat Spore',
  'Nail Pie',
  'Pale Cyst',
  'Pale Ore Soup',
  'Pale Ore',
  'Putrid Eggs',
  'Putrid Things',
  'Ruptureroot',
  'Salt Sprinklings',
  'Shadow Mold',
  'Shadow Orb',
  'Sharp Shadows',
  'Snail Pods',
  'Soul Totem',
  'Soup',
  'Spectral Core',
  'Vengefly',
  'Violet Confit',
  'Void Dreams',
  'Void Salts',
  'Void Spore',
  'Wild Grass',
  'Wires',
  'Yowlsect Eggs',
];
const MIMIC_PERSONALITIES = [
  'Adaptable',
  'Adventurous',
  'Altruistic',
  'Ambitious',
  'Articulate',
  'Athletic',
  'Charismatic',
  'Clever',
  'Competitive',
  'Courageous',
  'Crafty',
  'Cunning',
  'Diligent',
  'Eccentric',
  'Humorous',
  'Imaginative',
  'Inquisitive',
  'Intelligent',
  'Mystical',
  'Observant',
  'Opportunistic',
  'Outspoken',
  'Patient',
  'Quirky',
  'Resourceful',
  'Self-Reliant',
  'Silly',
  'Socially Savvy',
  'Spontaneous',
  'Stealthy',
  'Tireless',
  'Tough',
  'Whimsical',
];

button.addEventListener("click", function() {
  var pronouns = PRONOUNS[Math.floor((Math.random() * PRONOUNS.length))]
  document.getElementById("pronouns").innerHTML = pronouns;

  var possessive_pronoun = "";
  var referential_pronoun = "";
  switch (pronouns) {
    case "he/him":
      possessive_pronoun = "His";
      referential_pronoun = "him";
      break;
    case "she/her":
      possessive_pronoun = "Her";
      referential_pronoun = "her";
      break;
    case "they/them":
      possessive_pronoun = "Their";
      referential_pronoun = "them";
      break;
    case "fae/faer":
      possessive_pronoun = "Faer";
      referential_pronoun = "faer";
      break;
    case "xe/xem":
      possessive_pronoun = "Xir";
      referential_pronoun = "xem";
      break;
    case "it/its":
      possessive_pronoun = "Its";
      referential_pronoun = "it";
      break;
    case "ze/zir":
      possessive_pronoun = "Zir";
      referential_pronoun = "zir";
      break;
    case "ey/em":
      possessive_pronoun = "Eir";
      referential_pronoun = "em";
      break;
    case "ve/ver":
      possessive_pronoun = "Vis";
      referential_pronoun = "ver";
      break;
    case "grub/grubs":
      possessive_pronoun = "Grub";
      referential_pronoun = "grubs";
      break;
    default:
      possessive_pronoun = "Grub";
      referential_pronoun = "grub";
      break;
  }

  document.getElementById("pronounlabel").innerHTML = possessive_pronoun + ' pronouns are...';
  document.getElementById("foodlabel").innerHTML = possessive_pronoun + ' favorite food is...';
  document.getElementById("personalitylabel").innerHTML = possessive_pronoun + ' personality type is...';
  document.getElementById("congrats").innerHTML = 'Congratulations on making a new friend! Please make sure to take good care of ' + referential_pronoun + ".";
  button.innerHTML = "Make another friend!";

  var grubbyImage = document.getElementById("grubbyimage")
  grubbyImage.classList.add('rightside-up');
  grubbyImage.classList.remove('upside-down');

  var grubbynumber = Math.floor(Math.random() * 100);

  if (grubbynumber > 7) {
    document.getElementById("namelabel").innerHTML = 'Your grub\'s name is...';
    var name = GRUB_NAMES[Math.floor((Math.random() * GRUB_NAMES.length))]

    if(Math.random() >= 0.75 && !name.includes(" ")) {
      var surname = GRUB_SURNAMES[Math.floor((Math.random() * GRUB_SURNAMES.length))]
      while (name.trim().toLowerCase() === surname.trim().toLowerCase()) {
        surname = GRUB_SURNAMES[Math.floor((Math.random() * GRUB_SURNAMES.length))]
      }
      name = name + surname;
    }

    if(Math.random() >= 0.90) {
      var title = GRUB_TITLES[Math.floor((Math.random() * GRUB_TITLES.length))]
      while (name.trim().toLowerCase().includes(title.trim().toLowerCase())) {
        surname = GRUB_TITLES[Math.floor((Math.random() * GRUB_TITLES.length))]
      }
      name = title + name;
    }

    document.getElementById("grubname").innerHTML = name;
    document.getElementById("food").innerHTML = GRUB_FOODSTUFFS[Math.floor((Math.random() * GRUB_FOODSTUFFS.length))];
    document.getElementById("personality").innerHTML = GRUB_PERSONALITIES[Math.floor((Math.random() * GRUB_PERSONALITIES.length))];
    var grubbyImageData = GRUB_IMAGES[Math.floor((Math.random() * GRUB_IMAGES.length))];
    grubbyImage.innerHTML = `<img src=${grubbyImageData[0]} alt="${grubbyImageData[1]}" height="100px" width="100px">`;

    // Special case: flip if upside-down grub
    if (name == "Upside-Down Grub") {
      grubbyImage.classList.add('upside-down');
      grubbyImage.classList.remove('rightside-up');
    }
  }
  else {
    document.getElementById("namelabel").innerHTML = 'Your \"grub\'s\" name is...';
    document.getElementById("grubname").innerHTML = MIMIC_NAMES[Math.floor((Math.random() * MIMIC_NAMES.length))];
    document.getElementById("food").innerHTML = MIMIC_FOODSTUFFS[Math.floor((Math.random() * MIMIC_FOODSTUFFS.length))];
    document.getElementById("personality").innerHTML = MIMIC_PERSONALITIES[Math.floor((Math.random() * MIMIC_PERSONALITIES.length))];
    grubbyImage.innerHTML = '<img src="images/adoptable_grubs/mimic.png" alt="A mimic!" height="100px" width="100px">';
  }
});
