var button = document.createElement("button");
button.innerHTML = "Meet your new friend!";

var certificate = document.getElementById("certificate");
certificate.appendChild(button);
button.id = "idk_your_id_here";

const GRUB_IMAGES = [
  ["images/adoptable_grubs/adventure_grubby.png", "An adventuring grub"],
  ["images/adoptable_grubs/aggrub.png", "An aggrub"],
  ["images/adoptable_grubs/angel_grubby.png", "An angel grub"],
  ["images/adoptable_grubs/apple_grubby.png", "An apple grub"],
  ["images/adoptable_grubs/arg.png", "An alternate reality grub"],
  ["images/adoptable_grubs/art_grubby.png", "An artistic grub"],
  ["images/adoptable_grubs/astronaut_grubby.png", "An astronaut grub"],
  ["images/adoptable_grubs/beach_grubby.png", "A beach grub"],
  ["images/adoptable_grubs/beastling_grubby.png", "A grub with a beastling on its head"],
  ["images/adoptable_grubs/bee_grubby.png", "A bee grub"],
  ["images/adoptable_grubs/beetle_grubby.png", "A beetle grub"],
  ["images/adoptable_grubs/bird_grubby.png", "A parrot grub"],
  ["images/adoptable_grubs/blomgrub.png", "A blomgrub"],
  ["images/adoptable_grubs/blue_fire_grubby.png", "A  blue fire grub"],
  ["images/adoptable_grubs/broken_vessel_grubby.png", "A broken vessel grub"],
  ["images/adoptable_grubs/bubble_grubby.png", "A bubble grub"],
  ["images/adoptable_grubs/cactus_grubby.png", "A cactus grub"],
  ["images/adoptable_grubs/camoflauge_grubby.png", "A camoflauged grub"],
  ["images/adoptable_grubs/carrot_grubby.png", "A carrot grub"],
  ["images/adoptable_grubs/chef_grubby.png", "A chef grub"],
  ["images/adoptable_grubs/chocolate_grubby.png", "A chocolate grub"],
  ["images/adoptable_grubs/cloud_grubby.png", "A grub whose head is in the clouds"],
  ["images/adoptable_grubs/cogwork_grubby.png", "A cogwork grub"],
  ["images/adoptable_grubs/collector_grubby.png", "A grub holding a jar with the collector inside"],
  ["images/adoptable_grubs/corvid_grubby.png", "A corvid grub"],
  ["images/adoptable_grubs/crystal_grubby.png", "A crystal grub"],
  ["images/adoptable_grubs/cupcake_grubby.png", "A cupcake grub"],
  ["images/adoptable_grubs/delicate_flower_grubby.png", "A grub holding a delicate flower"],
  ["images/adoptable_grubs/dergy_grubby.png", "A dergy grub"],
  ["images/adoptable_grubs/devil_grubby.png", "A devil grub"],
  ["images/adoptable_grubs/disco_grubby.png", "A disco grub"],
  ["images/adoptable_grubs/ditto_grubby.png", "A ditto grub"],
  ["images/adoptable_grubs/earth_grubby.png", "An earth grub"],
  ["images/adoptable_grubs/eldergrub.png", "An elder grub"],
  ["images/adoptable_grubs/eye_grubby.png", "A grub with a very detailed eye"],
  ["images/adoptable_grubs/fancy_grubby.png", "A fancy grub with a monocle and hat"],
  ["images/adoptable_grubs/fire_grubby.png", "A fire grub"],
  ["images/adoptable_grubs/flannel_grubby.png", "A flannel grub"],
  ["images/adoptable_grubs/flea_grubby.png", "A fluffy flea grub"],
  ["images/adoptable_grubs/flower_grubby.png", "A flower grub"],
  ["images/adoptable_grubs/fluke_grubby.png", "A fluke grub"],
  ["images/adoptable_grubs/folly_grubby.png", "A folly grub"],
  ["images/adoptable_grubs/fox_grubby.png", "A fox grub"],
  ["images/adoptable_grubs/fox_moth_grubby.png", "A fox moth grub"],
  ["images/adoptable_grubs/frederick_grubby.png", "Frederick grub of spinning grub fame"],
  ["images/adoptable_grubs/galaxy_grubby.png", "A galaxy grub"],
  ["images/adoptable_grubs/ghost_grubby.png", "A ghost grub"],
  ["images/adoptable_grubs/glass_grubby.png", "A glass grub full of lumaflies"],
  ["images/adoptable_grubs/godseeker_grubby.png", "A godseeker grub"],
  ["images/adoptable_grubs/golden_grubby.png", "A grub made of gold"],
  ["images/adoptable_grubs/graduation_grubby.png", "A graduating grub"],
  ["images/adoptable_grubs/grimm_grubby.png", "A grimm grub"],
  ["images/adoptable_grubs/grub_husk_sentry_grubby.png", "A grub hust sentry"],
  ["images/adoptable_grubs/grubchu.png", "A grubchu"],
  ["images/adoptable_grubs/grubhat.png", "A grub with a hat"],
  ["images/adoptable_grubs/grumbchu.png", "A grumbchu"],
  ["images/adoptable_grubs/gunslinger_grubby.png", "A gunslinger grub"],
  ["images/adoptable_grubs/ice_grubby.png", "An ice grub"],
  ["images/adoptable_grubs/infection_grubby.png", "The infection, given grub form"],
  ["images/adoptable_grubs/kingsmould_grubby.png", "The void, given grub form"],
  ["images/adoptable_grubs/koi_grubby.png", "A koi grub"],
  ["images/adoptable_grubs/lifeblood_grubby.png", "A lifeblood grub with lifeblood wings"],
  ["images/adoptable_grubs/luigi_grubby.png", "A luigi grub"],
  ["images/adoptable_grubs/maggot_grubby.png", "A maggot grub"],
  ["images/adoptable_grubs/mario_grubby.png", "A mario grub"],
  ["images/adoptable_grubs/math_grubby.png", "TheMathGrub_314"],
  ["images/adoptable_grubs/mermaid_grubby.png", "A mermaid grub"],
  ["images/adoptable_grubs/mimic_grubby.png", "A grub in a mimic costume"],
  ["images/adoptable_grubs/missing_texture_grubby.png", "Error 404: Grub Not Found"],
  ["images/adoptable_grubs/moldy_grubby.png", "A moldy grub"],
  ["images/adoptable_grubs/monarch_grubby.png", "A monarch butterfly grub"],
  ["images/adoptable_grubs/moon_grubby.png", "A moon grub"],
  ["images/adoptable_grubs/mossy_grubby.png", "A mosskin-shaped grub"],
  ["images/adoptable_grubs/mothgrub.png", "A moth grub"],
  ["images/adoptable_grubs/mummy_grubby.png", "A grub wrapped in old cloth"],
  ["images/adoptable_grubs/mushroom_grubby.png", "A mushroom grub"],
  ["images/adoptable_grubs/panda_grubby.png", "A panda grub"],
  ["images/adoptable_grubs/paper_crane_grubby.png", "A grub whose head is covered in paper cranes"],
  ["images/adoptable_grubs/pearl_grubby.png", "A grub made of pearl"],
  ["images/adoptable_grubs/pengrub.png", "A penguin grub"],
  ["images/adoptable_grubs/pepper_grubby.png", "A pepper grub"],
  ["images/adoptable_grubs/pilot_grubby.png", "A pilot grub"],
  ["images/adoptable_grubs/porcelain_grubby.png", "A porcelain grub"],
  ["images/adoptable_grubs/portal_grubby.png", "A grub peeking through a portal"],
  ["images/adoptable_grubs/pride_grubby.png", "A rainbow-colored grub"],
  ["images/adoptable_grubs/pumpkin_grubby.png", "A grub with a pumpkin for a head"],
  ["images/adoptable_grubs/purpgrub.png", "A purple grub"],
  ["images/adoptable_grubs/radiance_grubby.png", "An old forgotten grub of light"],
  ["images/adoptable_grubs/radioactive_shrimp_grubby.png", "A radioactive shrimp grub (from Walmart)"],
  ["images/adoptable_grubs/radish_grubby.png", "A radish grub"],
  ["images/adoptable_grubs/rainbow_shade_grubby.png", "A rainbow shade grub"],
  ["images/adoptable_grubs/red_panda_grubby.png", "A red panda grub"],
  ["images/adoptable_grubs/regal_grubby.png", "A regal grub"],
  ["images/adoptable_grubs/rocket_grubby.png", "A grub in a rocket ship"],
  ["images/adoptable_grubs/ruby_grubby.png", "A ruby grub"],
  ["images/adoptable_grubs/sableye_grubby.png", "A grub with a jewel for an eye"],
  ["images/adoptable_grubs/salt_grubby.png", "A salt grub"],
  ["images/adoptable_grubs/sand_grubby.png", "A sand grub"],
  ["images/adoptable_grubs/sapphire_grubby.png", "A sapphire grub"],
  ["images/adoptable_grubs/shade_grubby.png", "A shade grub"],
  ["images/adoptable_grubs/shadow_grubby.png", "ShadowGrub7"],
  ["images/adoptable_grubs/shaman_grubby.png", "A shaman grub"],
  ["images/adoptable_grubs/shy_grubby.png", "A shy grub"],
  ["images/adoptable_grubs/silver_grubby.png", "A grub made of silver"],
  ["images/adoptable_grubs/sketch_grubby.png", "A sketch of a grub"],
  ["images/adoptable_grubs/skunk_grubby.png", "A skunk grub"],
  ["images/adoptable_grubs/sleepy_grubby.png", "A sleeping grub"],
  ["images/adoptable_grubs/snow_grubby.png", "A grub made of snow"],
  ["images/adoptable_grubs/soul_totem_grubby.png", "A soul totem grub"],
  ["images/adoptable_grubs/sour_grubby.png", "A sour grub"],
  ["images/adoptable_grubs/strawberry_grubby.png", "A strawberry grub"],
  ["images/adoptable_grubs/sun_grubby.png", "A sun grub"],
  ["images/adoptable_grubs/sunset_grubby.png", "A sunset grub"],
  ["images/adoptable_grubs/super_grubby.png", "A grub superhero"],
  ["images/adoptable_grubs/sushi_grubby.png", "A sushi grub"],
  ["images/adoptable_grubs/swallowtail_grubby.png", "A swallowtail butterfly grub"],
  ["images/adoptable_grubs/team_cherry_grubby.png", "A grub member of Team Cherry"],
  ["images/adoptable_grubs/tiger_grubby.png", "A tiger grub"],
  ["images/adoptable_grubs/trans_grubby.png", "A trans grub"],
  ["images/adoptable_grubs/treasure_grubby.png", "A treasure grub"],
  ["images/adoptable_grubs/ufo_grubby.png", "An alien grub in a little UFO"],
  ["images/adoptable_grubs/unicorn_grubby.png", "An unicorn grub"],
  ["images/adoptable_grubs/uumuu_grubby.png", "An uumuu grub"],
  ["images/adoptable_grubs/water_grubby.png", "A water grub"],
  ["images/adoptable_grubs/weaver_grubby.png", "A weaver grub"],
  ["images/adoptable_grubs/wingy_grubby.png", "A floating flying wingy grub"],
  ["images/adoptable_grubs/wormy_grubby.png", "A wormy grub"],
  ["images/adoptable_grubs/zebra_grubby.png", "A zebra grub"],
  ["images/adoptable_grubs/zeronium_grubby.png", "A zeronium grub"],
  ["images/grubby.png", "A grub!"]
];

const MIMIC_IMAGES = [
  ["images/adoptable_grubs/mimic.png", "A mimic"],
  ["images/adoptable_grubs/mimic.png", "A mimic"],
  ["images/adoptable_grubs/mimic.png", "A mimic"],
  ["images/adoptable_grubs/mimic.png", "A mimic"],
  ["images/adoptable_grubs/mimic.png", "A mimic"],
  ["images/adoptable_grubs/mimic.png", "A mimic"],
  ["images/adoptable_grubs/mimic.png", "A mimic"],
  ["images/adoptable_grubs/mimic.png", "A mimic"],
  ["images/adoptable_grubs/mimic.png", "A mimic"],
  ["images/adoptable_grubs/mimic.png", "A mimic"],
  ["images/adoptable_grubs/mimic.png", "A mimic"],
  ["images/adoptable_grubs/mimic.png", "A mimic"],
  ["images/adoptable_grubs/mimic.png", "A mimic"],
  ["images/adoptable_grubs/rainbow_mimic.png", "A rainbow mimic"],
  ["images/adoptable_grubs/red_mimic.png", "A red mimic"],
  ["images/adoptable_grubs/orange_mimic.png", "A orange mimic"],
  ["images/adoptable_grubs/blue_mimic.png", "A blue mimic"],
  ["images/adoptable_grubs/purple_mimic.png", "A purple mimic"]
];

const GRUB_NAMES = [
  "Acid Crawler",
  "Agitha",
  "Ambrose",
  "Baelfly Princess",
  "Beamer",
  "BeeBo",
  "Beeglob",
  "Belkite",
  "Bellowing Bog Beetle",
  "Birdfly",
  "Blastfly",
  "Blaze Salamander",
  "Blitznab",
  "Bloomguard",
  "Blossom",
  "Blueclaw Spitter",
  "Bobble Grub",
  "Bobbley",
  "Bogeeze",
  "Bolt",
  "Bop",
  "Bounceback",
  "Brigge",
  "Bristleback",
  "Bubbalou Grub",
  "Bubblebee",
  "Bubblebug",
  "Buddeet",
  "Buggly",
  "Bulb Grub",
  "Bulbly",
  "Bulby",
  "Bumble-Beezy",
  "Bumblebee",
  "Bumbles",
  "Bumbleshell",
  "Bumbleshout",
  "Bumblesnout",
  "Bumbly",
  "Bun Bun Grub",
  "Bunbun",
  "Burbly the Snaffler",
  "Burrly",
  "Burrow Grub",
  "Burrower Grub",
  "Burrowie",
  "Butterbug",
  "Buttercup",
  "Butters",
  "Buzz Bugger",
  "Buzz Burr",
  "Buzz One",
  "Buzz",
  "Buzz-Wing",
  "Buzzangler",
  "Buzzbeak",
  "BuzzBee",
  "Buzzbit",
  "Buzzboop",
  "Buzzbug",
  "Buzzbuzz",
  "Buzzby",
  "Buzzer",
  "Buzzfuzz",
  "Buzzitty",
  "Buzzler",
  "Buzzly",
  "Buzzsaw Grub",
  "Buzzscuttle",
  "Buzzwing",
  "Buzzy Bee",
  "Buzzy Blinker",
  "Buzzy the Bzzing Grub",
  "Buzzy",
  "Buzzzelworm",
  "Buzzzz",
  "Calitzi",
  "Cardigole",
  "Cashew Cutter",
  "Cave Glow Cocoon",
  "Chalkgrub",
  "Char Grub",
  "Charged Fat Grub",
  "Charmer Snail",
  "Charred Slugsaw",
  "Charvee",
  "Cheepy",
  "Chewbuggie",
  "Chewi",
  "Chewie",
  "Chillbumper",
  "Chillcoat",
  "Chimera Grub",
  "Chipmunk",
  "Chipotle",
  "Chipper",
  "Chirp",
  "Chirpee",
  "Chirper",
  "Chirping Grub",
  "Chirpsy",
  "Chirpy",
  "Chirruping Grub",
  "Chittering Glider",
  "Cholli",
  "Chomper",
  "Chompy the Chomping Grub",
  "Chub-Chub",
  "Chubb Bug",
  "Chubbles",
  "Chubbly",
  "Chubby Cheeks Grub",
  "Chubsy",
  "Chubwing",
  "Chugga-Bug",
  "Chunky Grubbles",
  "Chunky Grubby",
  "Churlbugg",
  "Churrworm",
  "Cinder-Grub",
  "Cinderbug",
  "Cinderpillar",
  "Clacco the Chirrup",
  "Clacksnout",
  "Clawcrawler",
  "Clawkin",
  "Clicky",
  "Clinger Grub",
  "Clitch",
  "Cloppy",
  "Cloth Wisp",
  "Coggles the Crawler",
  "Consume-a-lot",
  "Convenient Grub",
  "Cosy Grubbinator",
  "Crawly",
  "Creepster",
  "Crestog",
  "Cricket",
  "Crimson Skitterling",
  "Crispersnip",
  "Crossroad-cruncher",
  "Crumbly",
  "Crumpet",
  "Crunchlette",
  "Crystalline Crawler",
  "Crystallis",
  "Cuddlebud",
  "Cuddlee",
  "Cuddles",
  "Cuddlesquirm",
  "Cuddly Crawly",
  "Cuddly Grubs",
  "Curley",
  "Curli",
  "Curlicue",
  "Curly Q",
  "Curly the Curlicue Grub",
  "Curly",
  "Cutesy-Paws",
  "Cutie Caterpillar",
  "Cutie Chitter",
  "Cutie Pie Grub",
  "Cutie Wiggler",
  "Cuttlebitty",
  "Cuttleboo",
  "Cuttlebu",
  "Cuttlebug",
  "Cuttletrunk",
  "Cybuggler",
  "Daisy",
  "Dandy Grub",
  "Dartly",
  "Dawn Grub",
  "Deep Grub",
  "Deep Wriggler",
  "Deep-delver",
  "Deepglide the Wriggler",
  "DeepScale Grub",
  "Deepwing",
  "Deeree",
  "Dergy",
  "Desolation Moth",
  "Diamondeye",
  "Dirt Muncher",
  "Dirt Roo",
  "Dirtmoss",
  "Doodle Bug",
  "Doodle",
  "Dottie",
  "Dozy",
  "Dream Grub",
  "Drifter Worm",
  "Dugong",
  "Dusk Thief",
  "Duskwings",
  "Dust Drake",
  "Dust Grub",
  "Dust-bunny",
  "Dustfly",
  "Dustmound",
  "Dustwing",
  "Earendel",
  "Eileen the Hungry",
  "Entoza",
  "Essence Eater",
  "Extrest Grub",
  "Feathery Fritter",
  "Fidget",
  "Fifi the Friendly Grub",
  "Figglepop",
  "Figgolem",
  "Figgy",
  "Fire Dreamer",
  "Fire Lashbug",
  "Fizzworm",
  "Fizzy",
  "Flicker",
  "Flik",
  "Flipo",
  "Flitt",
  "Flitterbug",
  "Flitzy",
  "Flop 'Em",
  "Floppies",
  "Floppy",
  "Fluffa",
  "Flufftastic Grub",
  "Fluffy",
  "Fluffy-Feathers",
  "Flukemstrum",
  "Flutter",
  "Flutterbee",
  "Flutterbug",
  "Fracto",
  "Friggs",
  "Frilly",
  "Frizzlefly",
  "Fuddy",
  "Fumtum",
  "Fungal Emberfly",
  "Fungal Forager",
  "Fungal Wick",
  "Fungey Shrubster",
  "Fungicle",
  "Fungiface",
  "Fungmin",
  "Fungoar",
  "Fungoid",
  "Fungoidsting",
  "Fungus-Lord",
  "Fungusfly",
  "Fury Sprout",
  "Fuzzball",
  "Fuzzer",
  "Fuzzkins",
  "Fuzzlemuff",
  "Fuzzums",
  "Fuzzy Flutter",
  "Fuzzy Grub",
  "Fuzzy Nubble",
  "Fuzzy Wuzzy Grub",
  "Fuzzy",
  "Fuzzy-Puppy",
  "Fuzzywuzz",
  "Gallop Mudbug",
  "Gambril",
  "Garpede",
  "Gascoigne Grub",
  "Giggle Wiggler",
  "GiggleBug",
  "Gigglebuggie",
  "Giggles",
  "Gizmo",
  "Gizmo-Gobble",
  "Gizzlaw",
  "Gleeble",
  "Glibglop",
  "Glider",
  "Glimfly",
  "Glimglom",
  "Glimmer",
  "Glimmerfly Grove",
  "Glimworm",
  "Glintmoth-Grub",
  "Glitch",
  "Glitchy",
  "Glitter Grub",
  "Glitter",
  "Glitterbug",
  "Glittersnaps",
  "Glitterwing",
  "Glitz",
  "Glitzie",
  "Gloam",
  "Gloam-gnawer",
  "Glooble",
  "Gloom-Grub",
  "Gloomnip",
  "Gloomy",
  "Gloop",
  "Glooper",
  "Gloopy",
  "Glopling",
  "Glossy",
  "Glow Grub",
  "Glowbud",
  "Glowfly Grub",
  "Glowing Grub",
  "Glowing Snail",
  "Glowing Wriggler",
  "Glowmaggot",
  "Glowmo",
  "Glowwormshroom",
  "Glowygrub",
  "Glutterfly",
  "Gobble",
  "Gooble",
  "Goobling",
  "Gooey Grub",
  "Gooey",
  "Goomok",
  "Gorgot",
  "Gormaander",
  "Grave Wasp",
  "Gravity Grub",
  "Grealez",
  "Great Nailsage Sly",
  "Greber the Grub",
  "Greepbuzz",
  "Grey Hunter",
  "Greyfur",
  "Gribbler",
  "Gribby",
  "Grim Hornet",
  "Grimburly",
  "Grimfly",
  "Grimm Grub",
  "Grimmalle",
  "Grimmer",
  "Grimmermite",
  "Grimmite",
  "Gripper Grub",
  "Grit-Grub",
  "Gritburger",
  "Gritlily",
  "Grizzled Snoutworm",
  "Grobblefly",
  "Grogger",
  "Groggo",
  "Groob",
  "Groovin' Grubby",
  "Groovy Grub",
  "Gropler",
  "Grouchy",
  "Grounder",
  "Grub Blubb",
  "Grub Egg",
  "Grub Glimmer",
  "Grub Groove",
  "Grub Hopper",
  "Grub Knight",
  "Grub Nibble",
  "Grub Pie",
  "Grub Sluggard",
  "Grub Snugglers",
  "Grub Sweeper",
  "Grub the Builder",
  "Grub the Conqueror",
  "Grub Tubble",
  "Grub's Grotto",
  "Grub's Knees",
  "Grub-a-Boo",
  "Grub-a-Bub",
  "Grub-a-Bye",
  "Grub-a-Bye-Baby",
  "Grub-a-Dab-Do",
  "Grub-a-Doodle-Do",
  "Grub-a-Dub-Dub",
  "Grub-a-Fied",
  "Grub-a-Glow",
  "Grub-a-Knot",
  "Grub-a-Licious",
  "Grub-a-Lot",
  "Grub-a-Lub-Dub",
  "Grub-a-Lumpkin",
  "Grub-a-Mania",
  "Grub-a-Munchkin",
  "Grub-a-Nator",
  "Grub-a-Rama",
  "Grub-a-Roo",
  "Grub-a-Saurus",
  "Grub-a-Tangle",
  "Grub-a-Thon",
  "Grub-a-Tron",
  "Grub-a-Tude",
  "Grub-a-Wiggler",
  "Grub-Adore",
  "Grub-B-Rumble",
  "Grub-Grub-Grumble",
  "Grub-in-the-Rough",
  "Grub-N-Go",
  "Grub-o-Matic",
  "Grub-of-the-Deep",
  "Grub-on-the-Go",
  "Grub-tacular",
  "Grub-Tastic!",
  "Grub-tastic",
  "Grub-topia",
  "Grub-with-Glee",
  "Grubadon the Mighty",
  "Grubadon",
  "Grubadoo",
  "Grubador",
  "Grubadro",
  "Grubakin",
  "Grubaldo",
  "Grubalicious the Hungry",
  "Grubalicious",
  "Grubalina",
  "Grubanoff",
  "Grubard the Adventurous",
  "Grubard",
  "Grubaroo",
  "Grubb",
  "Grubbb",
  "Grubba-Do",
  "Grubbar",
  "Grubbarina the Fearless",
  "Grubbarina",
  "Grubber Bug",
  "Grubber",
  "Grubberella",
  "Grubberfest",
  "Grubberfly",
  "Grubberiffic",
  "Grubberific",
  "Grubbering",
  "Grubberlin",
  "Grubberling",
  "Grubbernaut",
  "Grubberoo",
  "Grubbers the Grubbing Grub",
  "Grubbers",
  "Grubbersnout",
  "Grubbert",
  "Grubberto the Wise",
  "Grubberto",
  "Grubbertus the Cautious",
  "Grubbertus",
  "Grubbies",
  "Grubbily-Goo",
  "Grubbin Huggins",
  "Grubbin",
  "Grubbing Along",
  "Grubbing Around",
  "Grubbing for Glory",
  "Grubbing for Gold",
  "Grubbing in the Dark",
  "Grubbing it Out",
  "Grubbing Out",
  "Grubbing the Night Away",
  "Grubbing",
  "Grubbit",
  "Grubble Blob",
  "Grubble Bop",
  "Grubble Bug",
  "Grubble Dazzle",
  "Grubble Grubs",
  "Grubble Gum",
  "Grubble Mc Grubberson",
  "Grubble the Grub",
  "Grubble",
  "Grubbleberry",
  "Grubblebottom",
  "Grubblebug",
  "Grubblefritz",
  "Grubblegum",
  "Grubblegut the Gluttonous",
  "Grubbles the Grub",
  "Grubbles",
  "Grubblet",
  "Grubbletina the Curious",
  "Grubbletina",
  "Grubbleton",
  "Grubbletop the Agile",
  "Grubbletop",
  "Grubblette",
  "Grubblewing",
  "Grubbleworm",
  "Grubblin' Gourmand",
  "Grubbling Along",
  "Grubblob",
  "Grubbly Bear",
  "Grubbly Goodness",
  "Grubbly Grubster",
  "Grubbly Wubbly",
  "Grubbly",
  "Grubbly-Go-Round",
  "Grubbo",
  "Grubboon",
  "Grubbun",
  "Grubbus the Playful",
  "Grubbus",
  "Grubby Dizzy-Goo",
  "Grubby Friend",
  "Grubby Galore",
  "Grubby Gatherings",
  "Grubby Glider",
  "Grubby Glimmer",
  "Grubby Groove Grub",
  "Grubby Grub-Grub",
  "Grubby Grubber",
  "Grubby Grubberoo",
  "Grubby Guts",
  "Grubby Little Buddies",
  "Grubby Little Grub",
  "Grubby McBuggy",
  "Grubby McFly",
  "Grubby the Grub",
  "Grubby the Grubber",
  "Grubby",
  "Grubby's Groove",
  "Grubby-Munchkin",
  "Grubby-Wubby-Do",
  "Grubbydoodle",
  "Grubcap",
  "Grubclaw",
  "Grubelicious",
  "Grubelina the Magnificent",
  "Grubelina",
  "Grubella",
  "Grubelord the Ruler",
  "Grubelord",
  "Gruber",
  "Gruberella",
  "Gruberino",
  "Grubetta",
  "Grubette",
  "Grubglider",
  "Grubguard the Thirsty",
  "Grubhat",
  "Grubikov",
  "Grubina",
  "Grubington",
  "Grubito",
  "Grubius Maximus",
  "Grubius",
  "Grubkin",
  "Gruble",
  "Grublet",
  "Grublin the Swift",
  "Grublin",
  "Grublina the Elegant",
  "Grublina",
  "Grubling Groove",
  "Grubling",
  "Grubloaf",
  "Grublus",
  "Grublyn",
  "Grubnose",
  "Grubolio",
  "Grubox",
  "Grubrick the Brave",
  "Grubrick",
  "Grubrose",
  "Grubs-a-Little",
  "Grubs-a-Lot",
  "Grubs-a-Moderate-Amount",
  "Grubsby",
  "Grubsey",
  "Grubsley",
  "Grubslinger the Quick",
  "Grubslinger",
  "Grubson the Mischievous",
  "Grubson",
  "Grubspike",
  "Grubstache",
  "Grubster the Great",
  "Grubster",
  "Grubsterino",
  "Grubswaddle",
  "Grubswiggle",
  "Grubsworth",
  "Grubsy",
  "Grubtastic",
  "Grubula the Enigmatic",
  "Grubula",
  "Grubules",
  "Grubulisk",
  "Grubulon the Stealthy",
  "Grubulon",
  "Grubulous Maximus",
  "Grubulous",
  "Grubulus",
  "Grubward",
  "Grubwatcher",
  "Grubzilla the Legendary",
  "Grubzilla",
  "Gruffa",
  "Grum",
  "Grumble Grub",
  "Grumble",
  "Grumblebee",
  "Grumblethorn",
  "Grumbleweed",
  "Grumblewort",
  "Grumm",
  "Grumps",
  "Grumpshrimp",
  "Grumpty",
  "Grumptysnout",
  "Grumpus",
  "Grumpy Grubkin",
  "Grumworm",
  "Grumwyrm",
  "Gruzzer",
  "Gruzzle",
  "Gruzzlet",
  "Gruzzly",
  "Guardian Grub",
  "Gully",
  "Gumbloom",
  "Gumbo",
  "Gumby",
  "Gummy Grub",
  "Gussel",
  "Gust Grub",
  "Gutterfly",
  "Happy",
  "Heavy Shade",
  "Herky",
  "Hiccup",
  "Highlighter",
  "Hipper",
  "Hive Keeper",
  "Hive Knight",
  "Hive-hopper",
  "Hivebark",
  "Hivebound Honey",
  "Hivekeeper",
  "Hivelord",
  "Hivewing",
  "Hollow Eel Grub",
  "Honey Buns",
  "Honey Hopper",
  "Honeybae",
  "Honeybun",
  "Honeycomb Grub",
  "Honeycomb",
  "Hooded Stranger",
  "Hopper Husky",
  "Hopper",
  "Hoppin' Joe",
  "Hoppit",
  "Hoppity",
  "Hopple",
  "Hoppy",
  "Hops",
  "Hotnest Grub",
  "Hovering Hermit",
  "Huffleg",
  "Hug-A-Bug",
  "Hushwing",
  "Inkback",
  "Iridbug",
  "Itchy",
  "Itsy Grub",
  "Jellie",
  "Jelly Grub",
  "Jen Jen",
  "Jeremothy",
  "Jeweldrop",
  "Jiggles",
  "Jiggly Joe",
  "Jiggly",
  "Jingle",
  "Jinglebug",
  "Jitter",
  "Jitterbug",
  "Jittery Grub",
  "Jittery",
  "Joltin' Grub",
  "JourneyBite",
  "Jumpcale",
  "Jumpfeather",
  "Jumppup",
  "King Grist",
  "King Mould",
  "Knickknacker",
  "Knightly Delight Grub",
  "Knitwisp",
  "Knocker-Noggin",
  "Labyrinth Grub",
  "Lantern Grub",
  "Lapotch",
  "Larveaureon",
  "Larvy",
  "Leafy",
  "Lichen Hopper",
  "Light Devourer",
  "Lightdarter",
  "Lil' Wriggler",
  "Lilygrub",
  "LittleMiso",
  "Loom Grub",
  "Loopy",
  "Lumafly",
  "Lumarok",
  "Luminary Grub",
  "Lurker",
  "Maggotcloud the Voracious",
  "Maggotry",
  "Maggretta",
  "Magmagrub",
  "Mantis Lord",
  "Mantisclaw",
  "Mantraphagus the Glutton",
  "Markfruit-Grub",
  "Mato Grub",
  "Mawlek",
  "Mawmaw",
  "Mender Grub",
  "Meregol",
  "Miffy",
  "Millie the Milling Grub",
  "Mire",
  "Mist-muncher",
  "Mite-Mite",
  "Mitey",
  "Mittens",
  "Moff",
  "Moffmittens",
  "Moldmarshal",
  "Molemite",
  "Moon Hopper",
  "Mordant the Ancient",
  "Moskit",
  "Mosquibug",
  "Mosquito",
  "Moss Grub",
  "Moss Matter",
  "Moss Mound Munchkin",
  "Mossbinder",
  "Mosskin",
  "Mosstail",
  "Moth Skitterling",
  "Moth Tribe Shaman",
  "Moth",
  "Mothexander",
  "Mothfly",
  "Mothgracious",
  "Mothnathan",
  "Mothwing",
  "Mothy",
  "Mr. Chomps",
  "Muckoo",
  "Mud Catterpillar",
  "Mud Puff",
  "Muffin",
  "Muffle Wisp",
  "Muncher",
  "Munchkin",
  "Munchmoth",
  "Munchy",
  "Mushaboom",
  "Mushroom Mage",
  "Mushy",
  "Mysticaline",
  "N4ll Beetle",
  "Nail Bug",
  "Nail Clipper",
  "Nail Grubble",
  "Nailbirb",
  "Nailbuzzer",
  "Nailclaw",
  "Nailshroom",
  "Nailwhirl",
  "Narelle",
  "Nature Grub",
  "Necromancer",
  "Nectar Eater",
  "Needlemane",
  "Needler",
  "Needleshell",
  "Needleworm",
  "Needloth",
  "Neleb",
  "Nevermore Grub",
  "Nezzrazz",
  "Nibble",
  "Nibblebug",
  "Nibbledonk",
  "Nibbler",
  "Nibbles",
  "Nibblesnout",
  "Nibbly",
  "Nibbs the Bug",
  "Niblet",
  "Nimble",
  "Nimbletrot",
  "Noble Nibbler",
  "Noctecoon",
  "Nodor",
  "Noodle",
  "Nubbins",
  "Oozy the Slime",
  "Orph the Nocto",
  "Ossean",
  "Pale Bearer",
  "Pale Wriggler",
  "Pancake Grub",
  "Pandemite",
  "Patter",
  "Paum",
  "Pebbles",
  "Peekaboo",
  "Peekagrub",
  "Peepers",
  "Pengrub",
  "Perky Pillbug",
  "Perky",
  "Perplexed Grub",
  "Phantom Spawn",
  "Pillar Grub",
  "Pillowbugs",
  "Pillurble",
  "Pinchy",
  "Pinstripe",
  "Pippa",
  "Pippin",
  "Pippy",
  "Pipsqueak",
  "Pitter Plodder",
  "Plated Clawsnail",
  "Plodder",
  "Plopkins",
  "Pluckabee",
  "Plumombre",
  "Plump",
  "Plush Bug",
  "Poko",
  "Ponder",
  "Poofy",
  "Poppet",
  "Poppy",
  "Pranceworm",
  "Prickle",
  "Prickly Grubbee",
  "Prickly Pod",
  "Puddle",
  "Puddles",
  "Puddley",
  "Puddly",
  "Puffapod",
  "Puffcoil",
  "Pupa",
  "Pupperoni",
  "Puru",
  "Quacky",
  "Quaggle",
  "Queen Mantis Shade",
  "Quirkle",
  "Quirper",
  "Radioactive Grub from Walmart",
  "Redcap",
  "Refurbished Grub",
  "Rickle",
  "Ripple",
  "Royal Grub",
  "Rustle",
  "Rustwasp",
  "Rustybug",
  "Safe Creeper",
  "Saltsquirm",
  "Salubra Skulker",
  "Sap Grub",
  "Sappyfly",
  "Scabblefly",
  "Scamp",
  "Scamper",
  "Scampers",
  "Scarabug",
  "Scavenger Grub",
  "Schnookie",
  "Scootaloo",
  "Scorupt",
  "Scree-Grub",
  "Scrobbler",
  "Scrubby",
  "Scrunchy",
  "Scurry",
  "Scuttle",
  "Scuttler",
  "Scuttles",
  "Scuttlesnout",
  "Scuttletail",
  "Scuttly",
  "Seeker Grub",
  "Shade Beast",
  "Shade Edge",
  "Shade Lurker",
  "Shadechomp",
  "Shadeclaw",
  "Shadefly",
  "Shadow",
  "Shadow Buzzer",
  "Shadow Flitter",
  "Shadow Grub",
  "Shadow Shimmer",
  "Shadow-Grub",
  "Shadowdancer",
  "Shelien",
  "Shell Hopper",
  "Shellback",
  "Shellglider",
  "Shimmerbug",
  "Shinee",
  "Shriek Bun",
  "Shrimbly",
  "Shyrtle",
  "Sideslip",
  "Silk Gatherer",
  "Silk Sensei",
  "Silksnail",
  "Silverhopper",
  "Silverwing",
  "Sinus",
  "Sirius",
  "Skedaddle",
  "Skeetle",
  "Skele Grub",
  "Skip",
  "Skipley",
  "Skipper Skittles",
  "Skipper",
  "Skipperhopper",
  "Skippety",
  "Sleepy Slugger",
  "Slick Grubster",
  "Slick",
  "Slickles",
  "Slime Galore",
  "Slimeball",
  "Slimebite",
  "Slimeface",
  "Slimefoot",
  "Slimemite",
  "Slimeton",
  "Slimy",
  "Slipper",
  "Slither",
  "Slitherwing",
  "Sliverbug",
  "Slivers",
  "Slop",
  "Slopper",
  "Sludge Eel",
  "Sludge",
  "Sludgeon",
  "Slumbercat",
  "Slurp",
  "Slurper",
  "Slurpy",
  "Slushie",
  "Slyder",
  "Smiley Grub",
  "Smiley Skitter",
  "Snaggle",
  "Snailer",
  "Snapperfly",
  "Snazzles",
  "Snibble",
  "Snibbob the Gluttonous",
  "Snicker Scuttler",
  "Snicker",
  "Snickerdoodle",
  "Snickety",
  "Snickle the Snurble",
  "Snookums",
  "Snoozy Grub",
  "Snuffly",
  "Snug",
  "Snuggle Bug",
  "Snuggle",
  "Snugglebug",
  "Snugglefly",
  "Snuggles",
  "Snuggles-Wiggles",
  "Snuggly",
  "Snuggy Grub",
  "Softmaker",
  "Solon",
  "Soot Slug",
  "Soul Grub",
  "Soulgazer",
  "Sparkle",
  "Sparklewiggler",
  "Sparklewing",
  "Sparky",
  "Speckle",
  "Spikeroot",
  "SpindlyDoodle",
  "Spiny Wurm",
  "Spiral Grub",
  "Spirit Grub",
  "Spittlegrub",
  "Sploshy Grub",
  "Spore Cloud",
  "Sprout",
  "Spudstar",
  "Squabble",
  "Squeaker",
  "Squeaks",
  "Squeakums",
  "Squeaky",
  "Squeeker",
  "Squiggle",
  "Squiggly",
  "Squiggy",
  "Squiglet",
  "Squigzy the Goop",
  "Squink",
  "Squirm Blurm",
  "Squirm Grub",
  "Squirm",
  "Squirmilla",
  "Squirming Seeker",
  "Squirmkin",
  "Squirmles",
  "Squirmly",
  "Squirmy",
  "Squirmz",
  "Squirt",
  "Squirtie",
  "Squirty",
  "Squish",
  "Squish-Munch",
  "Squishy",
  "Squishypaw",
  "Squisk",
  "Sroadign",
  "Stagmane",
  "Staincrab",
  "Stalwart Grub",
  "Stardustbug",
  "Stingbulb",
  "Stingtail",
  "Stingwing",
  "Stitchy",
  "Stone Skimmer",
  "Stonejaw",
  "Storm Crawler",
  "Strisp",
  "Stubby Grub",
  "Stumpy",
  "Sunny",
  "Supergrub",
  "Swarmlord",
  "Swarmstone",
  "Sweet Burrower",
  "Swoofulk",
  "Swoonworm",
  "Swoop",
  "Tadpink",
  "Tanglebloom",
  "Tart",
  "Tater Tot",
  "Tater",
  "Tendril",
  "The Fargus Flycatcher",
  "The Greasy Grub",
  "The Grub-inator",
  "The Molted Sentinel",
  "The Splinter Grub",
  "The Void Wing",
  "The Waking Shadow",
  "TheMathGrub314",
  "Thin-Mud",
  "Thistle Guard",
  "Thragg",
  "Three-Eye Grubshroom",
  "Thrumble",
  "Thumper",
  "Tibia",
  "Tickle",
  "Tickly",
  "Tinkerfly",
  "Tinny",
  "Tiny Troopers",
  "Tiny Turnip",
  "Tiny",
  "Tiny-Crawler",
  "Tippy-Toots",
  "Toblerone",
  "Tootle",
  "Trailblazer Grub",
  "Trappledoof",
  "Trinket",
  "Trot",
  "Trotter",
  "Truffle Mite",
  "Tubbelup",
  "Tubby",
  "Tuffly",
  "Tumble Grub",
  "Tumbly Bubbly",
  "Tummy Sprout",
  "Tunnel Grub",
  "Twiggle",
  "Twiggles",
  "Twiggy",
  "Twinkles",
  "Twitch",
  "Twitchy",
  "Upside-Down Grub",
  "Vengeful Spirit",
  "Venomer",
  "Vermilion",
  "Vespa Grub",
  "Violoid",
  "Viridescent Flytrap",
  "Viridian Grub",
  "Viscount Chorus",
  "Vivibulb",
  "Void Gazer",
  "Void Maze",
  "Wallworm",
  "Waltz",
  "Wambus",
  "Wandering Grub",
  "Watcher Knight",
  "Watchergleam",
  "Weebugs",
  "Wegsnar",
  "Whimby",
  "Whimsy",
  "Whiskers",
  "Whiskring",
  "Whitecap",
  "Wiggle n' Jiggle",
  "Wiggle",
  "Wiggler",
  "Wiggles the Wiggly Grub",
  "Wiggles",
  "Wigglesworth",
  "Wigglewobble",
  "Wigglez",
  "Wiggly Grub",
  "Wiggly Wisp",
  "Wiggly",
  "Wild Grub",
  "Wilkling",
  "Willow Weevil",
  "Wingmutter",
  "Wingy the Winged Grub",
  "Wire Bug",
  "Wisp Grub",
  "Wobble",
  "Wobbles",
  "Wobblewiggle",
  "Wolf Knight",
  "Wolfshell",
  "Woofer",
  "Woogle",
  "Wormly",
  "Wormtail",
  "Wormy",
  "Wrigglar",
  "Wriggle Grub",
  "Wriggle",
  "Wrigglee",
  "Wrigglepuff",
  "Wriggler",
  "Wrigglermoth",
  "Wrigglers",
  "Wriggles",
  "Wriggling Chap",
  "Wriggly",
  "Wrinkles",
  "Writhy",
  "Xeamless",
  "Yapper",
  "Zap",
  "Zote the Mighty"
];
const GRUB_SURNAMES = [
  " Beeglob",
  " Belkite",
  " Blob",
  " Bloomguard",
  " Bristleback",
  " Bubblebug",
  " Bug",
  " Bumble-Beezy",
  " Bumbleshell",
  " Bumblesnout",
  " Butterbug",
  " Buzzbit",
  " Buzzboop",
  " Buzzscuttle",
  " Buzzzelworm",
  " Chillcoat",
  " Chirruping Grub",
  " Chubwing",
  " Churlbugg",
  " Cinderbug",
  " Cinderpillar",
  " Clacksnout",
  " Clawcrawler",
  " Clawkin",
  " Crispersnip",
  " Crossroad-cruncher",
  " Crystallis",
  " Cuddlesquirm",
  " Cutesy-Paws",
  " Cuttlebitty",
  " Cuttletrunk",
  " Deep-delver",
  " Deepwing",
  " Dustmound",
  " Essence Eater",
  " Flitterbug",
  " Fluffy-Feathers",
  " Flutterbee",
  " Fungicle",
  " Fungmin",
  " Fungoidsting",
  " Fungusfly",
  " Fuzzlemuff",
  " Fuzzy-Puppy",
  " Gigglebug",
  " Gizmo-Gobble",
  " Gizzlaw",
  " Gleeble",
  " Glibglop",
  " Glimworm",
  " Glitter",
  " Glitterbug",
  " Glitterwing",
  " Gloam-gnawer",
  " Glopling",
  " Glowbud",
  " Greepbuzz",
  " Greyfur",
  " Gritburger",
  " Grobblefly",
  " Grub",
  " Grubberfly",
  " Grubbin",
  " Grubbing",
  " Grubbler",
  " Grubbydoodle",
  " Grubcap",
  " Grubclaw",
  " Grubglider",
  " Grublet",
  " Grumpshrimp",
  " Grumpty",
  " Gumbo",
  " Gutterfly",
  " Hive-hopper",
  " Hivebark",
  " Hivekeeper",
  " Hivelord",
  " Honeycomb",
  " Hushwing",
  " III",
  " Inkback",
  " IV",
  " IX",
  " Jeweldrop",
  " Knitwisp",
  " Knocker-Noggin",
  " Lapotch",
  " Lilygrub",
  " Lumafly",
  " Magmagrub",
  " Mantisclaw",
  " Mawmaw",
  " Mist-muncher",
  " Moldmarshal",
  " Mossbinder",
  " Mosstail",
  " Moth",
  " Needlemane",
  " Needler",
  " Needleworm",
  " Nezzrazz",
  " Nibblesnout",
  " Nimble",
  " Nimbletrot",
  " of the Endless MeeMawMaw",
  " Pandemite",
  " Pranceworm",
  " Redcap",
  " Rustybug",
  " Saltsquirm",
  " Scabblefly",
  " Scuttlesnout",
  " Shade",
  " Shadeclaw",
  " Shadefly",
  " Shadowdancer",
  " Shellback",
  " Shellglider",
  " Sideslip",
  " Silverbug",
  " Silverhopper",
  " Singbulb",
  " Skeetle",
  " Slimeball",
  " Slimeface",
  " Slimeite",
  " Slitherwing",
  " Slumbercat",
  " Snuggles-Wiggles",
  " Softmaker",
  " Sparklewiggler",
  " Spindlydoodle",
  " Spins-A-Little",
  " Spins-A-Lot",
  " Spins-A-Moderate-Amount",
  " Squish-Munch",
  " Stagmane",
  " Stardustbug",
  " Stingtail",
  " Stingwing",
  " Stonejaw",
  " Supergrub",
  " Tanglebloom",
  " the Adventurous",
  " the Agile",
  " the Brave",
  " the Cautious",
  " the Curious",
  " the Elegant",
  " the Enigmatic",
  " the Fearless",
  " the Gluttonous",
  " the Great",
  " the Hungry",
  " the Legendary",
  " the Magnificent",
  " the Mighty",
  " the Mischievous",
  " the Playful",
  " the Quick",
  " the Ruler",
  " the Stealthy",
  " the Swift",
  " the Void Wing",
  " the Wise",
  " Thin-Mud",
  " Tinkerfly",
  " Tiny-Crawler",
  " Tippy-Toots",
  " Trappledoof",
  " V",
  " VI",
  " VII",
  " VIII",
  " Vivibulb",
  " Wallworm",
  " Watchergleam",
  " Whiskring",
  " Wigglesworth",
  " Wigglewobble",
  " Wiggly",
  " Wingmutter",
  " Wobblewiggle",
  " Wolfshell",
  " Wrigglepuff",
  " Wrigglermoth",
  ", Beloved by All",
  ", Bringer of Joy",
  ", Destroyer of Worlds",
  ", Esq.",
  ", Grub of Grubs",
  ", Jr.",
  ", PhD.",
  ", Sr.",
  ", the Monarch of Grubland",
  "grub",
  "y"
];
const GRUB_TITLES = [
  "Admiral ",
  "Archduchess ",
  "Archduke ",
  "Baron ",
  "Baroness ",
  "Captain ",
  "Count ",
  "Countess ",
  "Dr. ",
  "Duchess ",
  "Duke ",
  "Earl ",
  "Emperor ",
  "Empress ",
  "General ",
  "Grand Vizier ",
  "Grub ",
  "Grubby ",
  "Judge ",
  "King ",
  "Knight ",
  "Lady ",
  "Lil\' ",
  "Lord ",
  "Madam ",
  "Marquioness ",
  "Marquis ",
  "Miss ",
  "Monarch ",
  "Mr. ",
  "Mrs. ",
  "Mx. ",
  "President ",
  "Prime Minister ",
  "Prince ",
  "Princess ",
  "Professor ",
  "Queen ",
  "Saint ",
  "Ser ",
  "Silly ",
  "Sir ",
  "Syr ",
  "The ",
  "The Brave ",
  "The Formidable ",
  "The Generous ",
  "The Grand ",
  "The Great ",
  "The Great Wizard ",
  "The Grubbiest ",
  "The Honourable ",
  "The Magnificent ",
  "The Mighty ",
  "Tsar ",
  "Viscount ",
  "Viscountess ",
  "Vizier "
];
const PRONOUNS = [
  'she/her',
  'she/her',
  'she/her',
  'she/her',
  'she/her',
  'she/her',
  'she/her',
  'she/her',
  'he/him',
  'he/him',
  'he/him',
  'he/him',
  'he/him',
  'he/him',
  'he/him',
  'he/him',
  'they/them',
  'they/them',
  'they/them',
  'they/them',
  'they/them',
  'they/them',
  'they/them',
  'they/them',
  'she/they',
  'he/they',
  'she/he',
  'he/it',
  'she/it',
  'they/it',
  'any/all',
  'fae/faer',
  'xe/xem',
  'it/its',
  'ze/zir',
  'ey/em',
  've/ver',
  'grub/grubs'
];
const GRUB_FOODSTUFFS = [
  'Anise',
  'Apple tree leaves',
  'Aster',
  'Azalea',
  'Bigflower Pawpaw',
  'Birch',
  'Birthwort Vines',
  'Cabbage',
  'Carrot',
  'Celery',
  'Cherry tree leaves',
  'Chervil',
  'Cilantro',
  'Culantro',
  'Clover',
  'Common Hoptree',
  'Coriander',
  'Daisies',
  'Dill',
  'Dutchman’s pipe',
  'Dwarf Pawpaw',
  'Fennel',
  'Golden Alexander',
  'Grapefruit Leaves',
  'Laurel',
  'Lemon Leaves',
  'Lilac',
  'Magnolia',
  'Mallow',
  'Milkweed',
  'Mint',
  'Netted Pawpaw',
  'Nettle',
  'Olive',
  'Pansies',
  'Parsley',
  'Parsnip',
  'Passionflowers',
  'Pipevine',
  'Plantains',
  'Plum tree leaves',
  'Prickly ash',
  'Queen Anne’s Lace',
  'Rose Leaves',
  'Roses Petals',
  'Rue',
  'Sassafras',
  'Sea Torchwood',
  'Smallflower Pawpaw',
  'Snapdragon',
  'Spicebush',
  'Strawberry',
  'Sweet Orange Leaves',
  'Tangerine Leaves',
  'Thistle',
  'Tuliptree',
  'Violets',
  'Virginia snakeroot',
  'Wild Lime',
  'Willow',
  'Woolly Pawpaw'
];
const GRUB_PERSONALITIES = [
  'Absentminded',
  'Adaptable',
  'Adventurous',
  'Anxious',
  'Articulate',
  'Brave',
  'Calm',
  'Clumsy',
  'Competitive',
  'Confident',
  'Courageous',
  'Crafty',
  'Curious',
  'Detail-oriented',
  'Determined',
  'Discerning',
  'Eccentric',
  'Explorer',
  'Focused',
  'Friendly',
  'Generous',
  'Heroic',
  'Idealistic',
  'Imaginative',
  'Independent',
  'Inquisitive',
  'Kind',
  'Loyal',
  'Meandering',
  'Optimistic',
  'Outspoken',
  'Patient',
  'Peaceful',
  'Persistent',
  'Personable',
  'Playful',
  'Quiet',
  'Quirky',
  'Reliable',
  'Reserved',
  'Resourceful',
  'Self-conscious',
  'Sensitive',
  'Shy',
  'Silly',
  'Sociable',
  'Solitary',
  'Sophisticated',
  'Spontaneous',
  'Tenacious',
  'Tireless',
  'Trusting',
  'Tough',
  'Whimsical'
];
const MIMIC_NAMES = [
  'Acid Licker',
  'Beardy Beetle',
  'Blobtodder',
  'Blocky Scarab',
  'Bonebite',
  'Burrower bug',
  'Buzzing Bimble',
  'Carrion Chomper',
  'Char Swarmer',
  'Chikkin Cringer',
  'Chirpy',
  'Chomp Bug',
  'Chomperkin',
  'Clampy Clinger',
  'Clicky Crawler',
  'Cling Dweller',
  'Clomping Chomper',
  'Crawlclaw',
  'Crawlfang',
  'Crawlipede',
  'Croakershrike',
  'Cutterfly',
  'Dirtminder',
  'Faltail',
  'Fire Bloon',
  'Fleabite',
  'Footwriggler',
  'Fossflow',
  'Fungoblin',
  'Funky Chompster',
  'Gabble Glutton',
  'Glopgrub',
  'Glowcap',
  'Glurcher',
  'Glutbuzz',
  'Glutterfly',
  'Gluttock',
  'Gnawer Beetle',
  'Goo Glutton',
  'Greedsquid',
  'Gribbly Gnat',
  'Gristly Grawl',
  'Gritskitter',
  'Grubkin Maw',
  'Grublurk',
  'Grubpup',
  'Grubspinner',
  'Grumble Fly',
  'Grunny Grounder',
  'Gummy Nibbler',
  'Gurgle Gulper',
  'Gutgorger',
  'Gutterfly',
  'Hortling',
  'Joltbug',
  'Jubilant Grobbler',
  'Junk Muddle',
  'Larva Lurker',
  'Ledger Lunger',
  'Maggot Muncher',
  'Mandible Mish-mash',
  'Mantis Muncher',
  'Mardel Grubber',
  'Mazegoose',
  'Meatshield',
  'Mining Masticator',
  'Mossling',
  'Muck Midge',
  'Muckdragger',
  'Munch Monster',
  'Muncher Shrimp',
  'Munchling',
  'Munchy Grubber',
  'Nectarhopper',
  'Needle Nibbler',
  'Nibble Nibbler',
  'Nibble Scuttle',
  'Oily Grubble',
  'Pick Pincher',
  'Plasterskimmer',
  'Plodworm',
  'Plumphog',
  'Pulpdigger',
  'Revelburrow',
  'Root Skulker',
  'Root wriggler',
  'Rumblegut',
  'Scalebrush',
  'Scrap Sniggerer',
  'Scrapfang',
  'Shellshade',
  'Shellshroom',
  'Shish Kabughan',
  'Skelechomp',
  'Skulleach',
  'Slime Pincer',
  'Slimy Slurker',
  'Sludge Slurper',
  'Sludgrin',
  'Slugslip',
  'Slurgslaw',
  'Smack Snack',
  'Smiggy Gnawer',
  'Soggy Spore',
  'Splutch',
  'Spore Sipper',
  'Squishgrub',
  'Stagnant Snacker',
  'Suddenhide',
  'Swooping Scourge',
  'Tarbag',
  'Troghopp',
  'Venomous Vor',
  'Web Wriggler',
  'Wiggleglom',
  'Wild swarm'
];
const MIMIC_SURNAMES = [
  " III",
  " IV",
  " IX",
  " Spins-A-Little",
  " Spins-A-Lot",
  " Spins-A-Moderate-Amount",
  " V",
  " VI",
  " VII",
  " VIII",
  ", Destroyer of Worlds",
  ", Esq.",
  ", Foolish One",
  ", Grand Wizard",
  ", Jr.",
  ", Lord of the Dark",
  ", PhD.",
  ", Shepherd of Despair",
  ", Slayer of Beasts",
  ", Sr.",
  ", That Which Threatens To Consume All",
  ", the Inescapable Darkness",
  ", the Un-Order",
  ", World-Eater"
];
const MIMIC_TITLES = [
  "Admiral ",
  "Archduchess ",
  "Archduke ",
  "Baron ",
  "Baroness ",
  "Captain ",
  "Count ",
  "Countess ",
  "Dr. ",
  "Duchess ",
  "Duke ",
  "Earl ",
  "Emperor ",
  "Empress ",
  "General ",
  "Grand Mimic ",
  "Grand Vizier ",
  "Judge ",
  "King ",
  "Knight ",
  "Lady ",
  "Lil\' ",
  "Lord ",
  "Madam ",
  "Marquioness ",
  "Marquis ",
  "Miss ",
  "Monarch ",
  "Mr. ",
  "Mrs. ",
  "Mx. ",
  "President ",
  "Prime Minister ",
  "Prince ",
  "Princess ",
  "Professor ",
  "Queen ",
  "Saint ",
  "Ser ",
  "Silly ",
  "Sir ",
  "Syr ",
  "The ",
  "Tsar ",
  "Viscount ",
  "Viscountess ",
  "Vizier "
];
const MIMIC_FOODSTUFFS = [
  'Blistermoss',
  'Blue Moth Strip',
  'Cables',
  'Deepnest Delights',
  'Dirt Clumps',
  'Dirt Sprouts',
  'Dreamfeast',
  'Dust Moth Bites',
  'Dusty Bun',
  'Effervescent Mush',
  'Failed Experiment Pie',
  'Fey Moth Egg',
  'Flukefin Soup',
  'Flukemarm Egg',
  'Flukemarm Eggs',
  'Fungal Clump Pudding',
  'Fungal Clump',
  'Fungal Core',
  'Fungal Wastes Mushrooms',
  'Fungus Drum',
  'Funicular Fruit',
  'Glowfly Lantern',
  'Glowing Egg',
  'Glowing Wort',
  'Gobbletoots',
  'Great Slashshroom',
  'Grub-style Cake',
  'Grub-style Crepes',
  'Grub-style Fish and Chips',
  'Grub-style Fried Chicken',
  'Grub-style Fries',
  'Grub-style Grilled Cheese',
  'Grub-style Noodle Bowl',
  'Grub-style Pizza',
  'Grub-style Rice',
  'Grubhoney',
  'Heavenly Bulb',
  'Hive Cluster',
  'Hiveborn Soup',
  'Hollow Knight Cake',
  'Hulking Carapace',
  'Jelly Jumps',
  'JELLY Lumpfish',
  'Matozaure Egg',
  'Mist Lurkers',
  'Mosskin Egg',
  'Mycelial Tufts',
  'Nail Bat Spore',
  'Nail Pie',
  'Pale Cyst',
  'Pale Ore Soup',
  'Pale Ore',
  'Putrid Eggs',
  'Putrid Things',
  'Ruptureroot',
  'Salt Sprinklings',
  'Shadow Mold',
  'Shadow Orb',
  'Sharp Shadows',
  'Snail Pods',
  'Soul Totem',
  'Soup',
  'Spectral Core',
  'Vengefly',
  'Violet Confit',
  'Void Dreams',
  'Void Salts',
  'Void Spore',
  'Wild Grass',
  'Wires',
  'Yowlsect Eggs',
];
const MIMIC_PERSONALITIES = [
  'Adaptable',
  'Adventurous',
  'Altruistic',
  'Ambitious',
  'Articulate',
  'Athletic',
  'Charismatic',
  'Clever',
  'Competitive',
  'Courageous',
  'Crafty',
  'Cunning',
  'Diligent',
  'Eccentric',
  'Humorous',
  'Imaginative',
  'Inquisitive',
  'Intelligent',
  'Mystical',
  'Observant',
  'Opportunistic',
  'Outspoken',
  'Patient',
  'Quirky',
  'Resourceful',
  'Self-Reliant',
  'Silly',
  'Socially Savvy',
  'Spontaneous',
  'Stealthy',
  'Tireless',
  'Tough',
  'Whimsical',
];

button.addEventListener("click", function () {

  var today = new Date();
  var dd = String(today.getDate()).padStart(2, '0');
  var mm = String(today.getMonth() + 1).padStart(2, '0'); //January is 0!
  var yyyy = today.getFullYear();

  today = mm + '/' + dd + '/' + yyyy;

  var grubbyImage = document.getElementById("grubbyimage")
  var adoptionImage = document.getElementById("grubimage")

  grubbyImage.classList.add('rightside-up');
  grubbyImage.classList.remove('upside-down');
  grubbyImage.classList.remove('spinner-slow');
  grubbyImage.classList.remove('spinner');
  grubbyImage.classList.remove('spinner-fast');
  adoptionImage.classList.add('rightside-up');
  adoptionImage.classList.remove('upside-down');

  if (Math.random() > .5) {
    adoptionImage.classList.add('face-right');
    grubbyImage.classList.add('face-right');
    adoptionImage.classList.remove('face-left');
    grubbyImage.classList.remove('face-left');
  } else {
    adoptionImage.classList.add('face-left');
    grubbyImage.classList.add('face-left');
    adoptionImage.classList.remove('face-right');
    grubbyImage.classList.remove('face-right');
  }

  var grubbynumber = Math.floor(Math.random() * 100);

  if (grubbynumber > 5) {
    document.getElementById("namelabel").innerHTML = 'Your grub\'s name is...';
    var name = GRUB_NAMES[Math.floor((Math.random() * GRUB_NAMES.length))]
    var pronouns = PRONOUNS[Math.floor((Math.random() * PRONOUNS.length))]
    var food = GRUB_FOODSTUFFS[Math.floor((Math.random() * GRUB_FOODSTUFFS.length))]
    var personality = GRUB_PERSONALITIES[Math.floor((Math.random() * GRUB_PERSONALITIES.length))]
    var image = GRUB_IMAGES[Math.floor((Math.random() * GRUB_IMAGES.length))]

    //Special Name Cases
    if (name == "Blossom") {
      food = "Parsley";
      personality = "Grubby";
      pronouns = "they/them";
      image = ["images/adoptable_grubs/blomgrub.png", "a blomgrub"];
    }
    if (name == "TheMathGrub314") {
      food = "Macaroni";
      personality = "Clever";
      pronouns = "he/him";
      image = ["images/adoptable_grubs/math_grubby.png", "TheMathGrub_314"];
    }
    if (name == "Shadow") {
      food = "Acorns";
      personality = "Creative";
      pronouns = "she/they";
      image = ["images/adoptable_grubs/shadow_grubby.png", "ShadowGrub7"];
    }
    if (name == "Paum") {
      food = "Green Curry";
      personality = "Fox";
      pronouns = "he/him";
      image = ["images/adoptable_grubs/fox_grubby.png", "A fox grub"];
    }
    if (name == "Pengrub") {
      image = ["images/adoptable_grubs/pengrub.png", "A penguin grub"];
    }
    if (name == "Peekagrub") {
      image = ["images/adoptable_grubs/grumbchu.png", "A grumbchu"];
    }
    if (name == "Moth") {
      image = ["images/adoptable_grubs/mothgrub.png", "A moth grub"];
    }
    if (name == "Grubhat") {
      image = ["images/adoptable_grubs/grubhat.png", "A grub with a hat"];
    }
    if (name == "Dergy") {
      image = ["images/adoptable_grubs/dergy_grubby.png", "A dergy grub"];
    }
    if (name == "Radioactive Grub from Walmart") {
      image = ["images/adoptable_grubs/radioactive_shrimp_grubby.png", "A radioactive shrimp grub (from Walmart)"];
    }
    if (name == "Zeronium") {
      image = ["images/adoptable_grubs/zeronium_grubby.png", "A zeronium grub"];
    }
    if (name == "Upside-Down Grub") {
      grubbyImage.classList.add('upside-down');
      grubbyImage.classList.remove('rightside-up');
      adoptionImage.classList.add('upside-down');
      adoptionImage.classList.remove('rightside-up');
    }

    if (Math.random() >= 0.90) {
      var title = GRUB_TITLES[Math.floor((Math.random() * GRUB_TITLES.length))]
      while (name.trim().toLowerCase().includes(title.trim().toLowerCase())) {
        title = GRUB_TITLES[Math.floor((Math.random() * GRUB_TITLES.length))]
      }
      if (name == "Blossom" || name == "Paum" || name == "TheMathGrub314") {
        while (title == "Archduchess " || title == "Baroness " || title == "Countess " || title == "Duchess " || title == "Empress " || title == "Lady " || title == "Madam " || title == "Marquioness " || title == "Miss " || title == "Mrs. " || title == "Princess " || title == "Queen " || title == "Viscountess ") {
          title = GRUB_TITLES[Math.floor((Math.random() * GRUB_TITLES.length))]
        }
      }
      if (name == "Shadow") {
        while (title == "Archduke " || title == "Baron " || title == "Count " || title == "Duke " || title == "Emperor " || title == "Lord " || title == "Sir " || title == "Marquis " || title == "Mr. " || title == "Prince " || title == "King " || title == "Viscount ") {
          title = GRUB_TITLES[Math.floor((Math.random() * GRUB_TITLES.length))]
        }
      }
      name = title + name;
    }

    if (Math.random() >= 0.75 && !name.includes(" ")) {
      var surname = GRUB_SURNAMES[Math.floor((Math.random() * GRUB_SURNAMES.length))]
      while (name.trim().toLowerCase() == surname.trim().toLowerCase()) {
        surname = GRUB_SURNAMES[Math.floor((Math.random() * GRUB_SURNAMES.length))]
      }
      if (surname == " Spins-A-Little") {
        grubbyImage.classList.add('spinner-slow');
      }
      if (surname == " Spins-A-Lot") {
        grubbyImage.classList.add('spinner-fast');
      }
      if (surname == " Spins-A-Moderate-Amount") {
        grubbyImage.classList.add('spinner');
      }
      name = name + surname;
    }

    if (Math.random() >= .999) {
      personality = "Pyromaniac";
    } else if (Math.random() >= .999) {
      personality = "Kleptomaniac";
    }

    document.getElementById("grubname").innerHTML = name;
    document.getElementById("food").innerHTML = food;
    document.getElementById("personality").innerHTML = personality;
    var grubbyImageData = image;
    grubbyImage.innerHTML = `<img src=${grubbyImageData[0]} alt="${grubbyImageData[1]}" height="100px" width="100px">`;

    document.getElementById("pronouns").innerHTML = pronouns;

    var personal_pronoun = "";
    var possessive_pronoun = "";
    var alt_possessive_pronoun = "";
    var referential_pronoun = "";
    var verb = "is";
    switch (pronouns) {
      case "he/him":
        personal_pronoun = "He";
        possessive_pronoun = "His";
        alt_possessive_pronoun = "His";
        referential_pronoun = "him";
        break;
      case "she/her":
        personal_pronoun = "She";
        possessive_pronoun = "Her";
        alt_possessive_pronoun = "Her";
        referential_pronoun = "her";
        break;
      case "they/them":
        personal_pronoun = "They";
        possessive_pronoun = "Their";
        alt_possessive_pronoun = "Their";
        referential_pronoun = "them";
        verb = "are";
        break;
      case "fae/faer":
        personal_pronoun = "Fae";
        possessive_pronoun = "Faer";
        alt_possessive_pronoun = "Faer";
        referential_pronoun = "faer";
        break;
      case "xe/xem":
        personal_pronoun = "Xe";
        possessive_pronoun = "Xir";
        alt_possessive_pronoun = "Xir";
        referential_pronoun = "xem";
        break;
      case "it/its":
        personal_pronoun = "It";
        possessive_pronoun = "Its";
        alt_possessive_pronoun = "Its";
        referential_pronoun = "it";
        break;
      case "ze/zir":
        personal_pronoun = "Ze";
        possessive_pronoun = "Zir";
        alt_possessive_pronoun = "Zir";
        referential_pronoun = "zir";
        break;
      case "ey/em":
        personal_pronoun = "Ey";
        possessive_pronoun = "Eir";
        alt_possessive_pronoun = "Eir";
        referential_pronoun = "em";
        verb = "are";
        break;
      case "ve/ver":
        personal_pronoun = "Ve";
        possessive_pronoun = "Vis";
        alt_possessive_pronoun = "Vis";
        referential_pronoun = "ver";
        break;
      case "she/they":
        personal_pronoun = "They";
        possessive_pronoun = "Her";
        alt_possessive_pronoun = "Their";
        referential_pronoun = "them";
        verb = "are";
        break;
      case "he/they":
        personal_pronoun = "They";
        possessive_pronoun = "His";
        alt_possessive_pronoun = "Their";
        referential_pronoun = "them";
        verb = "are";
        break;
      case "she/he":
        personal_pronoun = "He";
        possessive_pronoun = "Her";
        alt_possessive_pronoun = "His";
        referential_pronoun = "him";
        break;
      case "he/it":
        personal_pronoun = "It";
        possessive_pronoun = "His";
        alt_possessive_pronoun = "Its";
        referential_pronoun = "it";
        break;
      case "she/it":
        personal_pronoun = "It";
        possessive_pronoun = "Her";
        alt_possessive_pronoun = "Its";
        referential_pronoun = "it";
        break;
      case "they/it":
        personal_pronoun = "It";
        possessive_pronoun = "Their";
        alt_possessive_pronoun = "Its";
        referential_pronoun = "it";
        break;
      case "any/all":
        personal_pronoun = "She";
        possessive_pronoun = "Their";
        alt_possessive_pronoun = "Her";
        referential_pronoun = "him";
        break;
      case "grub/grubs":
        personal_pronoun = "Grub";
        possessive_pronoun = "Grubs";
        alt_possessive_pronoun = "Grubs";
        referential_pronoun = "grub";
        break;
      default:
        personal_pronoun = "Grub"
        possessive_pronoun = "Grub";
        alt_possessive_pronoun = "Grub";
        referential_pronoun = "grub";
        break;
    }

    document.getElementById("pronounlabel").innerHTML = possessive_pronoun + ' pronouns are...';
    document.getElementById("foodlabel").innerHTML = alt_possessive_pronoun + ' favorite food is...';
    document.getElementById("personalitylabel").innerHTML = possessive_pronoun + ' personality type is...';
    document.getElementById("congrats").innerHTML = 'Congratulations on making a new friend! Please make sure to take good care of ' + referential_pronoun + ".";
    
    var grubImageData = image;
    adoptionImage.innerHTML = `<img src=${grubImageData[0]} alt="${grubImageData[1]}" height="100px" width="100px">`;
    document.getElementById("grubcertificatename").innerHTML = name + " has hereby been adopted.";
    document.getElementById("grubfact").innerHTML = personal_pronoun + ' ' + verb + ' very ' + personality.toLowerCase() + '. ' + possessive_pronoun + ' favourite food is ' + food.toLowerCase() + '! Make sure to take good care of ' + referential_pronoun + ".";
    document.getElementById("currentdate").innerHTML = 'On this day, ' + today;
    button.innerHTML = "Make another friend!";
  }
  else {
    var mimicname = MIMIC_NAMES[Math.floor((Math.random() * MIMIC_NAMES.length))];
    var mimicpronouns = PRONOUNS[Math.floor((Math.random() * PRONOUNS.length))]
    
    if (Math.random() >= 0.75) {
      var mimictitle = MIMIC_TITLES[Math.floor((Math.random() * MIMIC_TITLES.length))]
      mimicname = mimictitle + mimicname;
    }

    if (Math.random() >= 0.75) {
      var mimicsurname = MIMIC_SURNAMES[Math.floor((Math.random() * MIMIC_SURNAMES.length))]
      if (mimicsurname == " Spins-A-Little") {
        grubbyImage.classList.add('spinner-slow');
      }
      if (mimicsurname == " Spins-A-Lot") {
        grubbyImage.classList.add('spinner-fast');
      }
      if (mimicsurname == " Spins-A-Moderate-Amount") {
        grubbyImage.classList.add('spinner');
      }
      mimicname = mimicname + mimicsurname;
    }

    var mimicfood = MIMIC_FOODSTUFFS[Math.floor((Math.random() * MIMIC_FOODSTUFFS.length))];
    var mimicpersonality = MIMIC_PERSONALITIES[Math.floor((Math.random() * MIMIC_PERSONALITIES.length))];

    document.getElementById("pronouns").innerHTML = mimicpronouns;
    var personal_pronoun = "";
    var possessive_pronoun = "";
    var alt_possessive_pronoun = "";
    var referential_pronoun = "";
    var verb = "is";

    switch (mimicpronouns) {
      case "he/him":
        personal_pronoun = "He";
        possessive_pronoun = "His";
        alt_possessive_pronoun = "His";
        referential_pronoun = "him";
        break;
      case "she/her":
        personal_pronoun = "She";
        possessive_pronoun = "Her";
        alt_possessive_pronoun = "Her";
        referential_pronoun = "her";
        break;
      case "they/them":
        personal_pronoun = "They";
        possessive_pronoun = "Their";
        alt_possessive_pronoun = "Their";
        referential_pronoun = "them";
        verb = "are";
        break;
      case "fae/faer":
        personal_pronoun = "Fae";
        possessive_pronoun = "Faer";
        alt_possessive_pronoun = "Faer";
        referential_pronoun = "faer";
        break;
      case "xe/xem":
        personal_pronoun = "Xe";
        possessive_pronoun = "Xir";
        alt_possessive_pronoun = "Xir";
        referential_pronoun = "xem";
        break;
      case "it/its":
        personal_pronoun = "It";
        possessive_pronoun = "Its";
        alt_possessive_pronoun = "Its";
        referential_pronoun = "it";
        break;
      case "ze/zir":
        personal_pronoun = "Ze";
        possessive_pronoun = "Zir";
        alt_possessive_pronoun = "Zir";
        referential_pronoun = "zir";
        break;
      case "ey/em":
        personal_pronoun = "Ey";
        possessive_pronoun = "Eir";
        alt_possessive_pronoun = "Eir";
        referential_pronoun = "em";
        verb = "are";
        break;
      case "ve/ver":
        personal_pronoun = "Ve";
        possessive_pronoun = "Vis";
        alt_possessive_pronoun = "Vis";
        referential_pronoun = "ver";
        break;
      case "she/they":
        personal_pronoun = "They";
        possessive_pronoun = "Her";
        alt_possessive_pronoun = "Their";
        referential_pronoun = "them";
        verb = "are";
        break;
      case "he/they":
        personal_pronoun = "They";
        possessive_pronoun = "His";
        alt_possessive_pronoun = "Their";
        referential_pronoun = "them";
        verb = "are";
        break;
      case "she/he":
        personal_pronoun = "He";
        possessive_pronoun = "Her";
        alt_possessive_pronoun = "His";
        referential_pronoun = "him";
        break;
      case "he/it":
        personal_pronoun = "It";
        possessive_pronoun = "His";
        alt_possessive_pronoun = "Its";
        referential_pronoun = "it";
        break;
      case "she/it":
        personal_pronoun = "It";
        possessive_pronoun = "Her";
        alt_possessive_pronoun = "Its";
        referential_pronoun = "it";
        break;
      case "they/it":
        personal_pronoun = "It";
        possessive_pronoun = "Their";
        alt_possessive_pronoun = "Its";
        referential_pronoun = "it";
        break;
      case "any/all":
        personal_pronoun = "She";
        possessive_pronoun = "Their";
        alt_possessive_pronoun = "Her";
        referential_pronoun = "him";
        break;
      case "grub/grubs":
        personal_pronoun = "Grub";
        possessive_pronoun = "Grubs";
        alt_possessive_pronoun = "Grubs";
        referential_pronoun = "grub";
        break;
      default:
        personal_pronoun = "Grub"
        possessive_pronoun = "Grub";
        alt_possessive_pronoun = "Grub";
        referential_pronoun = "grub";
        break;
    }

    document.getElementById("pronounlabel").innerHTML = possessive_pronoun + ' pronouns are...';
    document.getElementById("foodlabel").innerHTML = alt_possessive_pronoun + ' favorite food is...';
    document.getElementById("personalitylabel").innerHTML = possessive_pronoun + ' personality type is...';
    document.getElementById("congrats").innerHTML = 'Congratulations on making a new friend! Please make sure to take good care of ' + referential_pronoun + ".";

    document.getElementById("namelabel").innerHTML = 'Your \"grub\'s\" name is...';
    document.getElementById("grubname").innerHTML = mimicname;
    document.getElementById("food").innerHTML = mimicfood;
    document.getElementById("personality").innerHTML = mimicpersonality;
    
    var mimic_variant = MIMIC_IMAGES[Math.floor((Math.random() * MIMIC_IMAGES.length))]
    var mimicImageData = mimic_variant;
    grubbyImage.innerHTML = `<img src=${mimicImageData[0]} alt="${mimicImageData[1]}" height="100px" width="100px">`;
    adoptionImage.innerHTML = `<img src=${mimicImageData[0]} alt="${mimicImageData[1]}" height="100px" width="100px">`;
    document.getElementById("grubcertificatename").innerHTML = mimicname + " has hereby been adopted.";
    document.getElementById("grubfact").innerHTML = personal_pronoun + ' ' + verb + ' very ' + mimicpersonality.toLowerCase() + '. ' + possessive_pronoun + ' favourite food is ' + mimicfood.toLowerCase() + '! Make sure to take good care of ' + referential_pronoun + ".";
    document.getElementById("currentdate").innerHTML = 'On this day, ' + today;

  }
});

function downloadCertificate() {
    const element = document.getElementById("html-content-holder");

    html2canvas(element).then((canvas) => {
        const link = document.createElement("a");
        link.download = "certificate.png";
        link.href = canvas.toDataURL();
        link.click();
    })
}
